### ISSUE TITLE
how to get ITypeRoot

### ISSUE THREAD

**Issue by 1014661165** [eclipse-jdt/eclipse.jdt.core#103]
when i use ASTParser#createAST method to create a org.eclipse.jdt.core.dom.CompilationUnit with a single java file，i found that it's typeRoot field is null, but i want to use this field to call codeSelect method. What should i do to get it?

**Comment by stephan-herrmann** [comment]
`ITypeRoot` is part of the Java Model, not DOM AST, and hence `ASTParser` is not responsible for _producing_ `CompilationUnit#typeRoot`. This rather has to be _provided_ by the entity requesting the AST, like when you call `ASTParser.setSource(ITypeRoot source, int astLevel)`. 

By contrast, method `ASTParser.setSource(char[] source)` is primarily intended for use cases not having a workspace and thus not supporting any JavaModel operations.

As you seem to have the java file available, use it to directly obtain the `ITypeRoot` using `JavaCore.create(IFile)` (which returns `IJavaElement` rather than `ITypeRoot` only to account for `.jar` files in addition to `.class` and `.java`).
