### ISSUE TITLE
Canonical constructor of generic record not found if other constructor is present

### ISSUE THREAD

**Issue by robertvazan** [eclipse-jdt/eclipse.jdt.core#1085]
Not sure whether this is related to #799. I have the following record:

```java
public record GenericRecord<A>(int parameter) {
    public GenericRecord() {
        this(0);
    }
}
```

It is called like this:

```java
public class Test {
    public void test() {
        new GenericRecord<String>(0);
    }
}
```

Constructor call `new GenericRecord<String>(0)` is underlined with error "The constructor `GenericRecord<String>(int)` is undefined". Package Explorer however shows the file as error-free and the error does not appear in Problems view either. Sometimes one of these errors shows up in Problems and in Package Explorer, but if I delete the line and add it again, Problems and Package Explorer errors are cleared and the error is only visible in the file.

Eclipse: 2023-03
Java: 17
JDT: 3.19.0.v20230302-0300

**Comment by iloveeclipse** [comment]
Can confirm on latest master.
Note: if the default `GenericRecord()` constructor is removed, code compiles.

**Comment by iloveeclipse** [comment]
Hold on, the code compiles fine, it is **just the editor** that shows the error!

**Comment by iloveeclipse** [comment]
`<init>(void)` 
cool :-)

**Comment by srikanth-sankaran** [comment]
This is the same problem as reported by https://bugs.eclipse.org/bugs/show_bug.cgi?id=570399 but the fix there is inadequate and also introduces a completely redundant means of generating a canonical constructor using SyntheticMethodBinding's.

We need to get rid of one of the two mechanisms for generating canonical constructors implemented by 
1. org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.createDefaultConstructorForRecord(boolean, boolean) and
2. org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.addSyntheticRecordCanonicalConstructor()

I would argue that the SMB based approach is more befitting of how things are done in ECJ - though that position cannot be maintained 100% of the time.

Problem with generating at record parse time is that we don't know if the record declaration has a programmer supplied canonical constructor - so ecj takes the (ugly) approach of generating one eagerly and later if it turns out, there is a clash to delete the synthesized method.

See org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.methods() which deals with clash - the clash can arise from either of the redundant strategy.

I propose to provide a point fix for the present problem and raise a follow up ticket to deal with the elimination of two completely parallel apparatuses for this purpose.

**Comment by srikanth-sankaran** [comment]
I have a PR that fixes the problem, I will release for 4.29 M1

**Comment by srikanth-sankaran** [comment]
The PR for this ticket also resolves https://bugs.eclipse.org/bugs/show_bug.cgi?id=578989 - I have pushed the test  case from there.

**Comment by srikanth-sankaran** [comment]
Seems to be a popular defect!

The PR from for this ticket also resolves https://bugs.eclipse.org/bugs/show_bug.cgi?id=577351 - I have pushed the test case from there.
