### ISSUE TITLE
testBug566803 fails since I20230608-1800 on Java 17

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#1138]
testBug566803 fails four times since https://download.eclipse.org/eclipse/downloads/drops4/I20230608-1800/testResults.php

First fail:
```
Unexpected output running resulting class file for X.java: --[START]-- 0 @X$TestAnnFirst() ---[END]--- . ----------- Expected ------------ 0 @X.TestAnnFirst() ------------ but was ------------ 0 @X$TestAnnFirst()\n --------- Difference is ---------- expected:<0 @X[.TestAnnFirst()]> but was:<0 @X[$TestAnnFirst()\n ]>

junit.framework.ComparisonFailure: Unexpected output running resulting class file for X.java:
--[START]--
0 @X$TestAnnFirst()
---[END]---
.
----------- Expected ------------
0 @X.TestAnnFirst()
------------ but was ------------
0 @X$TestAnnFirst()\n

--------- Difference is ----------
expected:<0 @X[.TestAnnFirst()]> but was:<0 @X[$TestAnnFirst()\n
]>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:266)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:242)
at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runTest(AbstractRegressionTest.java:3602)
at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runTest(AbstractRegressionTest.java:3252)
at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runConformTest(AbstractRegressionTest.java:1973)
at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runConformTest(AbstractRegressionTest.java:1970)
at org.eclipse.jdt.core.tests.compiler.regression.TypeAnnotationTest.testBug566803(TypeAnnotationTest.java:7058)
```

There seem to be a dollar sign instead of a dot and an extra new line in the output.

**Comment by iloveeclipse** [comment]
This is a regression from 03658fd4ac29c267869c3ad9cf20788feb200e6e.

Note: the test does **not** fail if running it with Java 19+, but fails on Java 17 (see https://download.eclipse.org/eclipse/downloads/drops4/I20230608-1800/testResults.php).

@srikanth-sankaran : please take a look.

**Comment by srikanth-sankaran** [comment]
This is a brand new test - so this failure cannot be a regression. 

Also there is no real eclipse issue here - the behavior change from 17 to 19 comes about because of this JDK bug fix:
https://bugs.openjdk.org/browse/JDK-8281462 - annotation printing now uses canonical names rather than binary type names. And the test is coded to expect the up to date behavior.

Of course, Eclipse tests should be resilient - I can either disable the test for compliance < 19 or make the test expect alternate output. 

@iloveeclipse I am not fully acquainted with whether we run the tests also with other VM/JDK implementations. In the distant past, we used to run with IBM's VM/JDK too for instance.

**Comment by srikanth-sankaran** [comment]
One way to circumvent the problem is to make the test more explicit by printing canonical name thereby completely sidestepping the spot where there is a behavior change due to https://bugs.openjdk.org/browse/JDK-8281462  - i.e don't use toString() implicitly by coding the test to say:

```
for (int i = 0; i < as.length; i++) {
	System.out.println(i + " " + as[i]);
}
```

but rather say:
```
for (int i = 0; i < as.length; i++) {
    System.out.println(i + " " + as[i].annotationType().getCanonicalName());
}
```

**Comment by iloveeclipse** [comment]
> I am not fully acquainted with whether we run the tests also with other VM/JDK implementations. In the distant past, we used to run with IBM's VM/JDK too for instance.

So far we run "official" SDK tests with two JDK versions: 17 (on Mac/Win/Linux) and "latest stable" which is 20 (on Linux only), both versions should be from Adoptium.
