### ISSUE TITLE
Code to create a UnresolvedReferenceBinding

### ISSUE THREAD

**Issue by MartinWitt** [eclipse-jdt/eclipse.jdt.core#1186]
Hey,

At spoon, we have a bug in our code with `UnresolvedReferenceBinding`. The only reproduction code we have is with `java.lang.Class`. Are you aware of some other small code which produces a `UnresolvedReferenceBinding`? I looked through your tests and haven't found one.

**Comment by srikanth-sankaran** [comment]
'UnresolvedReferencedBinding' is a proxy of sorts for an as yet uninternalized class file. The relevant class files will be internalized just when needed - during which process additional URBs may he created for other referenced classes which may get internalized at a still later time on demand. 

This is JDTs way of coping with information overload - rather than dive deep into every class encountered thereby exploding memory usage and start up time. 

This does not look like an actionable defect report. Unless additional information is forthcoming which would help us understand the problem this ticket is a nop.
