### ISSUE TITLE
[21] Switch with record pattern reported even when all permitted subtypes are present

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#1244]
Consider the following code:

```
sealed interface I permits A, B, C {}
final class A   implements I {}
final class B   implements I {}
record C(int j) implements I {} 
record Box(I i) {}
public class X1 {
	@SuppressWarnings("preview")
	public static int testExhaustiveRecordPatterns(Box box) {
	    return switch (box) { 
	        case Box(A a) -> 0;
	        case Box(B b) -> 1;
	        case Box(C c) -> 2;
	   };
	}
}
```

The three record patterns with all permitted types cover all possible cases. However, we still report this for missing default. We already check for the exhaustiveness when sealed types are present in a type pattern. But we don't do that when they are nested in record patterns.

**Comment by mpalat** [comment]
Adding further
From https://cr.openjdk.org/~gbierman/jep440+441/jep440+441-20230612/specs/patterns-switch-record-patterns-jls.html#jls-14.11.1.1

(a)

sealed interface I permits A, B, C {}
final class A implements I {}
final class B implements I {}
record C(int j) implements I {} // Implicitly final
record Box(I i) {}

int testExhaustiveRecordPatterns(Box b) {
return switch (b) { // Exhaustive!
case Box(A a) -> 0;
case Box(B b) -> 1;
case Box(C c) -> 2;
};
}

(b)

Determining whether this switch block is exhaustive requires the analysis of the combination of the record patterns. The set { Box(I i) } covers the type Box, and the original set of patterns { Box(A a), Box(B b), Box(C c) } can be rewritten to the set { Box(I i) }. This is because the set { A a, B b, C c } reduces to the pattern I i (because the same set covers the type I), and thus the set { Box(A a), Box(B b), Box(C c) } reduces to the pattern Box(I i).

However, rewriting a set of record patterns is not always so simple. For example:

record IPair(I i, I j){}

int testNonExhaustiveRecordPatterns(IPair p) {
return switch (p) { // Not Exhaustive!
case IPair(A a, A a) -> 0;
case IPair(B b, B b) -> 1;
case IPair(C c, C c) -> 2;
};
}
