### ISSUE TITLE
Syntactic analysis for @Nullable field has no effect in false branch of conditional expression

### ISSUE THREAD

**Issue by Burtsev-Alexey** [eclipse-jdt/eclipse.jdt.core#1311]
Environment
Operating System: Windows 10 x64
JDK version: 20
IDE: 
- Visual Studio Code version: 1.81.1  Java extension version: 1.21.0
- NetBeans IDE 18
- Eclipse IDE 2023-06

Steps To Reproduce
Write any Java code that access org.springframework.lang.Nullable no matter how you check for NULL.
See screenshot.

Current Result
Always show warning "Potential null pointer access"

Expected Result
Some null check code exists that is considered as null check done, so warning is not shown. I understand that t is hard to analyze complex null check scenarios, but I'll be happy if simple code like "if (obj!=null) {obj.foo()}" will not show warning.
![2023-08-25_17-15-53](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/957102/b6d05d29-32ab-4fbc-a328-7128c9e85ca5)

**Comment by fbricon** [comment]
I confirm the same behavior is seen in Eclipse 2023-09-M3

**Comment by iloveeclipse** [comment]
> I confirm the same behavior is seen in Eclipse 2023-09-M3

Could you please attach simple self contained Eclipse project that shows the problem?

**Comment by fbricon** [comment]
There you go: [nullable-bug.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/12441803/nullable-bug.zip)
<img width="1299" alt="Screenshot 2023-08-25 at 18 53 41" src="https://github.com/eclipse-jdt/eclipse.jdt.core/assets/148698/9684f958-3513-4a02-bbd1-c04656ce23c9">

null-analysis works as expected if the @Nullable-annotated variable is a method parameter, as opposed to a class field.

**Comment by iloveeclipse** [comment]
OK, so itis about fields only, right, and you expect if the code checks null on a field before dereferencing it **after reading its value again**, no warning should be shown? But that is wrong in general, assuming the non final field can be written by other thread between null checkand dereference.

I see of course that the field is private and class doesn't allow to modify it by some setter, so that ideally should be taken into null analysis. However I have no insights how exactly null analysis is implemented in compiler.

@stephan-herrmann : please help to understand if this is just a known limitation of the null analysis in JDT or a bug.

**Comment by fbricon** [comment]
> But that is wrong in general, assuming the non final field can be written by other thread between null checkand dereference.
right I thought about that, but that means any non-final Nullable field would trigger the error, without any way to prevent it?

**Comment by iloveeclipse** [comment]
Only @stephan-herrmann knows that...

**Comment by Burtsev-Alexey** [comment]
You gen null warning in any case no matter how you check.
[test.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/12442742/test.zip)
![2023-08-25_21-47-04](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/957102/9c232d38-cc42-4119-9a1b-dcb6a9db1abc)

**Comment by iloveeclipse** [comment]
> no matter how you check.

You know that field value may change between null check and dereferencing? If sou want write safe code, load field value into local variable first and there shouldn't be warnimg anymore.

**Comment by Burtsev-Alexey** [comment]
> You know that field value may change between null check and dereferencing?
I agree that field can change. Bit this is a warning of POTENIAL null pointer access, it is not supposed to be 100% accurate. 99.9999% of time value will not become null.
> If sou want write safe code, load field value into local variable first and there shouldn't be warnimg anymore.
1) You code will become a mess if load every field of input argument structure in methods.
2) This is paranoid, even if you copy to local field you can't be 100% sure, some other process may interfere with your stack\memorry and change local var to null after you checked it.

Nullable annation is suposed to be a hint for developer: "could be null, dont forget to check", currently it's unusable because I see hundreds of uninformative NPE warnings even when I do !=null

**Comment by stephan-herrmann** [comment]
While I'm traveling and until I find the time for a more detailed answer here's the main reference on this topic:
* https://help.eclipse.org/latest/topic/org.eclipse.jdt.doc.user/tasks/task-using_null_annotations.htm?cp=1_3_9_0
  * search for **The case of fields**

**Comment by Burtsev-Alexey** [comment]
> While I'm traveling and until I find the time for a more detailed answer here's the main reference on this topic:
> 
> * https://help.eclipse.org/latest/topic/org.eclipse.jdt.doc.user/tasks/task-using_null_annotations.htm?cp=1_3_9_0
>   
>   * search for **The case of fields**

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/957102/4a1bc1d7-aacf-41b0-97e1-43fb9fb2f1d8)

**Comment by stephan-herrmann** [comment]
> **With the given option enabled** the above code will not be flagged ...

so, have to tried enabling that option?

**Comment by Burtsev-Alexey** [comment]
> > **With the given option enabled** the above code will not be flagged ...
> 
> so, have to tried enabling that option?

Yes. I have tried settings that option enabled, but it didn't changed anything - problem remains. I have even tried restarting IDE.

Also may I suggest settings that option "On" by default if you fix it. I think this is the expected behavior 99.9% time.


![2023-08-27_16-33-06](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/957102/bb8b6f85-3c4b-4948-bb8b-4f826b73f824)

**Comment by stephan-herrmann** [comment]
We indeed have a bug, and a simple workaround for now: apply quick assist "Invert conditional expression" to change the code to:
```
		return (text != null) ? text.length() : 0;
```
which is correctly understood by the compiler.

**Comment by stephan-herrmann** [comment]
I changed the title, as it is only a very specific situation, where the implementation does not work as expected.

In fact, it works as _designed_, because "syntactic analysis for fields" was intentionally designed in a very narrow way, to clearly communicate that this is different from flow analysis.

For conditional expressions, though, I admit that requiring to use `!= null` rather than `== null` is a bit too obscure.

**Comment by stephan-herrmann** [comment]
Some conceptual comments:

Some years back, the JDT team had an intense discussion whether or not true flow analysis for fields should be added, but we found that any promise to do so would raise expectations that we are not able to meet.

Only those variables, that are _owned_ by the current piece of code can meaningfully participate in local flow analysis. I.e., intra procedural flow analysis is suitable for local variables, not for fields (unless Java would adopt some concept of "ownership", "alias control" ... in some future version).

That's why nullable fields are inevitably painful in this regard.

> I agree that field can change. Bit this is a warning of POTENTIAL null pointer access, it is not supposed to be 100% accurate.

Since the introduction of `TYPE_USE` annotations, null analysis **is** in fact designed _towards_ the goal of 100% accuracy in the following sense: error free code should never throw NPE. I'm aware that most users are satisfied if only some NPEs are statically detected, but in order to serve those with higher expectations the design starts with all the painful strictness needed for high levels of safety and only from there we provide options for softening the analysis. Starting from lax rules and adding options for additional strictness is not a road I consider manageable.

Syntactic analysis for fields is one of the options for a pragmatic compromise.

> If you are so pedantic you can separate cases of a) no check done at all, b) check is not thread safe. So developers can switch off "b" when code is single threaded.

It is a common misconception that only concurrency can invalidate static analysis for fields. That view is valid only in the narrowest case where absolutely no code is executed between the null check and the dereference. Consider:
```
   if (this.f != null && foo()) System.out.print(this.f.toString());
```
It is super easy to construct `foo()` in a way to let this line of code throw NPE (which is _not_ possible when using a local variable instead).

In fact even this code can be completed such that it throws NPE:
```
   if (this.f != null) OtherClass.print(this.f.toString();
```
because loading `OtherClass` may invoke code that modifies `f` - no concurrency needed.

Yes this is pedantic, I know.

Syntactic analysis for fields is the compromise, allowing a little bit of analysis even for nullable fields.

> Also may I suggest settings that option "On" by default if you fix it.

This has been considered, but unless a user explicitly ticks "syntactic null analysis for fields" they will never know there is a difference between this and flow analysis. (As a consequence all these differences will be reported as "bugs" of the compiler time and again).
