### ISSUE TITLE
[21][record patterns] type inference with wildcard

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#1336]
Given the following, ecj gives an error - investigate
```
record R<T> ( T t) {}
public final class X { 
    private static boolean foo(R<?> r) {
        if (r instanceof R(String s)) { // ecj gives failure "Pattern of type ? is not compatible with type java.lang.String"
         return true;
        }
        return false;
    }
 
    public static void main(String argv[]) {
        System.out.println(foo(new R<>(new String("hello"))));
    }
}
```

Record Type inference as per - https://cr.openjdk.org/~gbierman/jep440+441/jep440+441-20230612/specs/patterns-switch-record-patterns-jls.html#jls-18.5.5

**Comment by stephan-herrmann** [comment]
@mpalat  aside from a missing `<T>`  (and bad formatting) I could find no problem with your test. I wrapped it in a proper junit and uploaded it as PR #1338 to make sure we're on the same page. On my machine it passes, let's see what jenkins thinks about it.

**Comment by stephan-herrmann** [comment]
Oops, inference isn't even triggered, because `RecordPattern.shouldInitiateRecordTypeInference()` answers `false`. If I force it to say `true`, then I see the mentioned error. 

Is `shouldInitiateRecordTypeInference()` confused about `PatternVariablesVisitor.hasPatternVar` vs. `PatternVariablesVisitor.typeElidedVar`??

**Comment by stephan-herrmann** [comment]
Next oops: if I tweak `shouldInitiateRecordTypeInference()` to answer `true` then the debugger tells me that `RecordPattern.inferRecordParameterization()` **never** looks at `RecordPattern.patterns`, i.e., the `String s` part is not considered at all. Hence there is no reason to "improve" from `R<?>` but during `setAccessorsPlusInfuseInferredType()` the inner pattern raises the error within `isPatternTypeCompatible()`.

This kind of pattern is called a deconstructor pattern, right? The linked spec, however, doesn't contain the word "deconstructor". So, where would I find specification how those are to be treated?

**Comment by stephan-herrmann** [comment]
Inching along:
* the correct lingo as per the spec is "a record pattern with nested patterns"
* the nested pattern needs no inference, type of `s` is trivially `String`.
* From "_When [...] the pattern does not provide type arguments for R_" I infer that providing type arguments is a legit thing in record patterns:

```
			if (r instanceof R<String>(String s)) {
				return !s.isEmpty();
			}
```
This gives a different error: `Type R<capture#1-of ?> cannot be safely cast to R<String>`, OK, so we can write type arguments, but if those are different from the declared type arguments of `r` then we're back to unsafe cast, instead of inference. (javac does not complain about unsafe cast).

Back to the original test, I suspect that javac implements some additional rule that is missing in JLS 18.5.5. Smth about generating additional constraints from nested patterns.

**Comment by mpalat** [comment]
> #1338

@stephan-herrmann let me try to answer the queries over the course of the day as and when I have an answer - First, I was trying out this patch - https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1339 - this was used to "refine" the decision algorithm for "shouldInititiateRecordPatternInference()" - this is in no way a state to merge - just a WIP patch for investigation at the best... Please have a look at the same - here I return true  with an effective OR of either a "var" [as in "var name" or a non-parameterized type - I believe it is more universal than the set that satisfies hasPatternVar -[ I should reduce the set with your suggestion of hasPatternVar which would exclude non-pattern variable cases, I agree].

**Comment by mpalat** [comment]
> * From "_When [...] the pattern does not provide type arguments for R_" I infer that providing type arguments is a legit thing in record patterns:

From https://cr.openjdk.org/~gbierman/jep440+441/jep440+441-20230612/specs/patterns-switch-record-patterns-jls.html#jls-15.20.2 --
Prior to Java SE 16, the ReferenceType operand of a type comparison operator was required to be reifiable ([4.7](https://docs.oracle.com/javase/specs/jls/se19/html/jls-4.html#jls-4.7)). This prevented the use of a parameterized type unless all its type arguments were wildcards. The requirement was lifted in Java SE 16 to allow more parameterized types to be used.. 

> 
> Back to the original test, I suspect that javac implements some additional rule that is missing in JLS 18.5.5. Smth about generating additional constraints from nested patterns.

Stephan, am suspecting that we are not comparing the right type in RecPattern.setAccessorsPlusInfuseInferredType()
				if (p.isPatternTypeCompatible(expressionType, scope)) { //<== here
From https://cr.openjdk.org/~gbierman/jep440+441/jep440+441-20230612/specs/patterns-switch-record-patterns-jls.html#jls-15.20.2,

"The following rules apply when instanceof is the pattern match operator:
...

The Pattern must be applicable at the type of the expression RelationalExpression ([14.30.3]"
(https://cr.openjdk.org/~gbierman/jep440+441/jep440+441-20230612/specs/patterns-switch-record-patterns-jls.html#jls-14.30.3)), or a compile-time error occurs.

Now, moving on to https://cr.openjdk.org/~gbierman/jep440+441/jep440+441-20230612/specs/patterns-switch-record-patterns-jls.html#jls-14.30.3, 
"A pattern p is said to be applicable at a type T if one of the following rules apply:
...
A record pattern with type R and pattern list L is applicable at type T if (i) T is checked cast convertible to R, and (ii) for every pattern p appearing in L, if any, p is applicable at the type of the corresponding component field in R ([5.5](https://cr.openjdk.org/~gbierman/jep440+441/jep440+441-20230612/specs/patterns-switch-record-patterns-jls.html#jls-5.5))."
and then recursively following for the nested case, we have the Type Pattern rule in the same section albeit the case being the first item, ie "A type pattern that declares a pattern variable of a reference type U is applicable at a reference type T if T is checked cast convertible to U ([5.5](https://cr.openjdk.org/~gbierman/jep440+441/jep440+441-20230612/specs/patterns-switch-record-patterns-jls.html#jls-5.5))."

shouldn't the check be 
		} else if (!checkCastTypesCompatibility(scope, patternType, other, this.expression, true)) {
 
rather than the current version

		} else if (!checkCastTypesCompatibility(scope, other, patternType, this.expression, true)) {

**Comment by stephan-herrmann** [comment]
> First, I was trying out this patch - #1339 - this was used to "refine" the decision algorithm for "shouldInititiateRecordPatternInference()" - this is in no way a state to merge - just a WIP patch for investigation at the best

I marked the PR as draft for that exact reason. But we need the real test and real code experiments for our discussion.

Yes, lets first figure out, whether inference should run at all for this example, and what rule and implementation is responsible for that.

**Comment by mpalat** [comment]
> I marked the PR as draft for that exact reason. But we need the real test and real code experiments for our discussion.
> 

The code is real.. Only thing is that the angle brackets with T inside is being interpreted by git as some marker and disappears.. if you just click on Edit then you can see the code in full.

> Yes, lets first figure out, whether inference should run at all for this example, and what rule and implementation is responsible for that.

from 
18.5.5 Record Pattern Type Inference
When a record pattern ([14.30.1](https://cr.openjdk.org/~gbierman/jep440+441/jep440+441-20230612/specs/patterns-switch-record-patterns-jls.html#jls-14.30.1)) for a generic record class R appears in a context in which values of a type T will be matched against it, and the pattern does not provide type arguments for R, the type arguments are inferred, as described below. 
With the above statement, I believe we need to do the inference.. do you think otherwise?

**Comment by stephan-herrmann** [comment]
@mpalat let's back up a bit (and forget about my second commit in #1338):  you asked me about type inference, but apparently I first need to understand the bigger picture, asking questions like:

1. what is the type of the pattern?
2. is the pattern applicable?
3. how should the pattern be evaluated?
4. ...

**Ad (1):** either the declared `ReferenceType` is the type of the pattern, or if this type is a raw type "_then the type of the record pattern is inferred, as described in 18.5.5_" \[[14.30.1](https://cr.openjdk.org/~gbierman/jep440+441/jep440+441-20230612/specs/patterns-switch-record-patterns-jls.html#jls-14.30.1)]. Ergo: inference should be attempted when only seeing a raw type with no further checks needed.

_**=> Which part of the spec led to consulting `containsTypeElidedPatternVar` for this decision? This looks unmotivated to me.**_

**(1.a):** given that type inference should be invoked, what outcome do we expect, what do we see? If I modify `shouldInitiateRecordTypeInference()` to comply with the above understanding, then inference will be invoked and it will conclude that the pattern has type `R<?>`.  Whether or not that is correct will need to be judged in larger context.

**Ad (2):** [14.30.3](https://cr.openjdk.org/~gbierman/jep440+441/jep440+441-20230612/specs/patterns-switch-record-patterns-jls.html#jls-14.30.3) tells us "_A record pattern with type R and pattern list L is applicable at type T if (i) T is checked cast convertible to R, and (ii) for every pattern p appearing in L, if any, p is applicable at the type of the corresponding component field in R (5.5)._"
* R = `R<?>`
* L = \[ String s ]
* T = |R| (type of the expression `r`)  _**=> I'm guessing here about erasure, I can't readily see how the spec determines `T`**_
 
so we need to check
* is `|R|` checked cast convertible to `R<?>`?
* is `String p` applicable at `?`, i.e., is `?` checked cast convertible to `String` _**=> Since `?` is not a type, we might need to first erase this to `Object`, does the spec say anything here?**_

**Ad (3):** The given value `r` needs to be checked if it can be cast to `R<?>` without `CCE` and recursively `r.t()` needs to be cast to `String` without `CCE`.

Once we get clarity about the parts **_emphasized bold italic_**, then everything should nicely fall into place.

**Comment by stephan-herrmann** [comment]
Saying "erasure" was wrong, types of expressions may need to be **captured**.

**Comment by stephan-herrmann** [comment]
@mpalat focusing on where to apply capture looks promising, just opportunistically inserting one call to `capture(..)` gave me a full PASS on RecordPatternTest. Still we need to apply more scrutiny, so I came across the following inconsistency between spec and impl:

See spec inside 18.5.5 bullet 3: "_If T is a parameterized type, let Tc be the result of capture conversion (5.1.10) applied to T, and let Z1, ..., Zk (k ≥ 0) be the type variables produced by capture that are type arguments in Tc. (This includes type variables produced by the capture conversion in this step, and type variables produced by capture conversion elsewhere.) Let β1, ..., βk (k ≥ 0) be inference variables, and let θ be the substitution[Z1:=β1, ..., Zk:=βk]. T' is Tc θ._"

Corresponding impl is inside `deriveTPrime()`, where I see these discrepancies:
* calls `parameterizedWithWildcard()` which is not called for in the spec
* I don't see any `capture()` here or inside `getTPrimeArgumentsAndCreateBounds()`.

Perhaps this impl stanza was written against a previous spec version and needs to be updated?

**Comment by mpalat** [comment]
> => Which part of the spec led to consulting `containsTypeElidedPatternVar` for this decision? This looks unmotivated to me.
hmm.. point taken. The spec did not talk about it. this may not be required. only raw type check may be required as you meant

**Comment by stephan-herrmann** [comment]
To avoid mixing up things I created a fresh PR with more serious proposals of code changes: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1341
