### ISSUE TITLE
Maven artifact org.eclipse.jdt.annotation has wrong Maven model version in pom

### ISSUE THREAD

**Issue by agentgt** [eclipse-jdt/eclipse.jdt.core#1416]
Hi @stephan-herrmann the Eclipse Null annotations have the wrong Maven pom version in its deployed pom to maven central:

```xml
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0</modelVersion> <!-- This should be 4.0.0 -->
  <groupId>org.eclipse.jdt</groupId>
  <artifactId>org.eclipse.jdt.annotation</artifactId>
  <version>2.2.700</version>
...
</project>
```

Apparently this causes issues in Gradle.

https://github.com/jstachio/jstachio/issues/236

**Comment by stephan-herrmann** [comment]
I haven't the slightest who changed this to "4.0", see https://github.com/eclipse-jdt/eclipse.jdt.core/blame/master/org.eclipse.jdt.annotation/pom.xml  -- that has always been "4.0.0".

OTOH, I would indeed expect maven to recognize 4.0 and 4.0.0 as the same version, since they never enforce a specific number of segments, missing segments should be considered to be "0", no? But frankly, I never fully understood maven concept of version numbers ;)

@sravanlakkimsetti @elsazac do you have any idea what might have happened to that pom: https://repo1.maven.org/maven2/org/eclipse/jdt/org.eclipse.jdt.annotation/2.2.700/org.eclipse.jdt.annotation-2.2.700.pom

**Comment by dsyer** [comment]
See here for the origin of the change: https://github.com/eclipse-platform/eclipse.platform/issues/180

**Comment by stephan-herrmann** [comment]
> See here for the origin of the change: [eclipse-platform/eclipse.platform#180](https://github.com/eclipse-platform/eclipse.platform/issues/180)

Thanks, that confirms there's nothing to be done in JDT and good @merks already fixed the tooling bug.

**Comment by agentgt** [comment]
@stephan-herrmann Ideally a new artifact would be published such that its pom file has the correct model version. I believe they fixed the tooling we just need a release now. Do you know of a timeline of when that could happen?

Other JDT artifacts are published it seems at a faster pace which makes sense as they change frequently but not the annotations. 

I'm just concerned it will be years before with we have a newer `org.eclipse.jdt:org.eclipse.jdt.annotation` and it may hurt Eclipses null analysis adoption.

It looks like @sravanlakkimsetti did the last release of it or at least version change: https://github.com/eclipse-jdt/eclipse.jdt.core/commit/b7baf569cc545057401d6c9dd28b7b46ab02a391
 
I'm sorry to be a pain about it.

**Comment by merks** [comment]
So this should probably be reopened to increase the minor version.

**Comment by stephan-herrmann** [comment]
> So this should probably be reopened to increase the minor version.

ok

**Comment by stephan-herrmann** [comment]
Pom looks correct again: https://repo1.maven.org/maven2/org/eclipse/jdt/org.eclipse.jdt.annotation/2.2.800/org.eclipse.jdt.annotation-2.2.800.pom :+1:
