### ISSUE TITLE
The target type of this expression must be a functional interface at Main:5

### ISSUE THREAD

**Issue by Luro02** [eclipse-jdt/eclipse.jdt.core#1427]
Code to reproduce the issue:
```java
import java.util.List;
import java.util.function.Supplier;

public class Main {
    private static final List<Pair<Supplier<String>>> ATTRIBUTE = List.of(new Pair<>(String::new));

    record Pair<T>(T first) {}

    public static void main(String[] args) {}
}
```
With `javac 17.0.1` the code compiles.

In eclipse: `Type mismatch: cannot convert from List<Main.Pair<Object>> to List<Main.Pair<Supplier<String>>>`
JDT message: `The target type of this expression must be a functional interface at Main:5`

I used JDT version `3.34.0`.

**Comment by stephan-herrmann** [comment]
Thanks, I tentatively assigned it to myself, although, experience tells that there's a possibility that JLS does not give us the tools to resolve this problem. Reason for pessimism: to reproduce the problem, we need type inference in all three levels:
* `<T> List<T> of(T)` -- what is `<T>`?
* `new Pair<>` -- what is the omitted type argument?
* `String::new` -- which functional interface should this implement?

From previous issues we know that in order to handle such nested inference javac does more than whats specified in JLS. And any approximation of javac's behavior outside the spec will by definition remain an approximation only.

Obviously, there's a bunch of workarounds for now, matching the above list of levels, each of the following RHS is accepted by ecj:
* `List.<Pair<Supplier<String>>>of(new Pair<>(String::new));`
* `List.of(new Pair<Supplier<String>>(String::new));`
* `List.of(new Pair<>(new Supplier<String>() { @Override public String get() { return null; } }));`

But let's first see, if perhaps a simple code bug prevents ecj from finding the inference solution.

**Comment by stephan-herrmann** [comment]
Some variants:

1. change record to regular class with corresponding constructor -> same error :x: 
2. assign `new Pair<>(String::new)` to a new local of appropriate type -> ecj accepts :white_check_mark: 
3. assign `String::new` to a new local variable ->  ecj accepts :white_check_mark: 
4. use custom `of` method to avoid overloading of `List.of(..)` -> same error :x:
5. replace diamond `new Pair<>` with invocation of a custom `<T> Pair<T> createPair(T t)` -> ecj accepts :white_check_mark: 

I always assumed that all three levels of nesting are relevant for the bug, but additionally the shape of the middle poly invocation is relevant: generic method invocation is understood, diamond is not. This might serve for a clue where the bug lies.

**Comment by stephan-herrmann** [comment]
A bug in our mechanics of representing a constructor with different binding types at different phases during inference.
