### ISSUE TITLE
Array type is getting generated in the .class where java.lang.Object should have been generated

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-jdt/eclipse.jdt.core#147]
Based on https://github.com/eclipse-equinox/p2/issues/92

for the code [return methodHandle.invoke(self);](https://github.com/eclipse-equinox/p2/blob/245b912c1d082336e68f0df882b601dd458fd706/bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/internal/p2/metadata/expression/Member.java#L73), We are generating 
```
INVOKEVIRTUAL java/lang/invoke/MethodHandle.invoke ([Ljava/lang/Object;)Ljava/lang/Object;
```

**Comment by sravanlakkimsetti** [comment]
Notify @jarthana

**Comment by jarthana** [comment]
This is turns out to be a result of consuming "java/lang/invoke/MethodHandle" with --release option. This particular class file, when --release is used is having wrong content. I.e., the RuntimeVisibleAnnotations attribute is missing. As a result of this, the @PolymorphicSignature from the MethodHandle#invoke() is ignored, which further affects how we generate code for a variable arity method. As far JDT is concerned, the relevant code is in Statement#generateArguments() where binding.isVarargs() returns false since the method is not created as polymorphic. If we have a version of JDK with correct .class files, we should take them and close this as not eclipse.

**Comment by sravanlakkimsetti** [comment]
I went ahead with looking into class file changes between java 17.0.1 and 17.0.3. There are no changes between them. I am really not confident on calling this as fixed in 17.0.3 yet. 

Will continue investigation on this one.

**Comment by jarthana** [comment]
> I went ahead with looking into ct.sym file changes between java 17.0.1 and 17.0.3. There are no changes between them. I am really not confident on calling this as fixed in 17.0.3 yet.
> 
> Will continue investigation on this one.

Actually, I find the produced .class file having the same issue with 17.0.3.1 as well.

**Comment by sravanlakkimsetti** [comment]
We are depending on PolymorphicSignature annotation to determine whether the method is polymorphic or not. But according to https://docs.oracle.com/javase/specs/jls/se18/html/jls-15.html#jls-15.12.3

_A method is signature polymorphic if all of the following are true:_

- _It is declared in the java.lang.invoke.MethodHandle class or the java.lang.invoke.VarHandle class._
- _It has a single variable arity parameter ([§8.4.1](https://docs.oracle.com/javase/specs/jls/se18/html/jls-8.html#jls-8.4.1)) whose declared type is Object[]._
- _It is native._

I guess we should deduce PolymorphicSignature annotation based on above definition

**Comment by sravanlakkimsetti** [comment]
Here is the sample code
```
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.reflect.Method;


public class Cl {
	public final Object invoke(Object self) throws Throwable {

			Method method = null;
			try {
				MethodHandle methodHandle = MethodHandles.lookup().unreflect(method );
				return methodHandle.invoke(self);
			} catch (IllegalArgumentException e) {
				throw e;
			} 
		}
}
```
