### ISSUE TITLE
Cleanup with Java 21 support removes wrong code

### ISSUE THREAD

**Issue by frankbenoit** [eclipse-jdt/eclipse.jdt.core#1480]
With installed Java 21 in Eclipse, but in a project using Java 17 only
````
public class EBug {
    
    class A{
        
    }
    class A1 extends A {
        
    }
    class A2 extends A {
        
    }
    class A3 extends A {
    }
    
    public static void main(String[] args) {
        Object o = "";
        if( o instanceof A1 a1) {
            
        } else if( o instanceof A2 a1) {
            
        } else if( o instanceof A3 a1) {
            
        } else  {
            
        }
    }
}

````
Calling cleanup, afterwards the 2nd case is gone:
````
public class EBug {

    class A {

    }

    class A1 extends A {

    }

    class A2 extends A {

    }

    class A3 extends A {

    }

    public static void main(String[] args) {
        final Object o = "";
        if (o instanceof final A1 a1) {

        } else if (o instanceof final A3 a1) {

        } else {

        }
    }
}


````
See example project with the clean up settings
[EclipseBug.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/12750746/EclipseBug.zip)

**Comment by jjohnstn** [comment]
Problem has been diagnosed to a change in ast level 21 whereby the PatternInstanceofExpression has been changed to deprecate the right hand operand and replace it with a Pattern.  The cleanup that is causing the problem is the remove unreachable block cleanup which in this case was comparing the first instanceof expression against the second in the else if.  The comparison was using the old deprecated right hand operand check and in this case they are equal since they aren't being filled in so the cleanup determined that the else if wasn't necessary.  I have prepared a fix for the matcher code so that it will do the correct thing based on the ast level.
