### ISSUE TITLE
[22] JEP 463: Implicitly Declared Classes and Instance Main Methods (Second Preview)

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#1640]
Evolve the Java programming language so that students can write their first programs without needing to understand language features designed for large programs. Far from using a separate dialect of the language, students can write streamlined declarations for single-class programs and then seamlessly expand their programs to use more advanced features as their skills grow. 

https://openjdk.org/jeps/463

for latest : https://cr.openjdk.org/~gbierman/jep463/latest/

**Comment by mpalat** [comment]
@datho7561 would you be looking into this?

**Comment by datho7561** [comment]
Yes, I'll take a look into this

**Comment by jarthana** [comment]
I am taking over this. Just had a quick glance and here are my observations so far:
1. There's not much change between Java 21 and 22. Only major change wrt grammar I see is the name change to simple compilation unit (let's say SCU).
2. We are unable to create .class file with this patch because the special characters we use < and > are disallowed. I don't see why we can't do what Javac does - use the name of the file itself. This should work as long as we work with file based CUs.
3. The spec says SCU has an implicit constructor and cannot have an explicit constructor. Now it doesn't say whether the code inside can refer the implicit constructor. This patch allows it, but Javac rejects. This needs to be checked with spec authors, perhaps.

**Comment by datho7561** [comment]
> I don't see why we can't do what Javac does - use the name of the file itself.

For context, the reason the PR was using the invalid name was as a hack to get around the class being able to be referenced in other classes. This definitely needs to be changed, and might not be trivial.

**Comment by jarthana** [comment]
> > I don't see why we can't do what Javac does - use the name of the file itself.
> 
> For context, the reason the PR was using the invalid name was as a hack to get around the class being able to be referenced in other classes. This definitely needs to be changed, and might not be trivial.

OK, I see you were trying to mimic the Javac behavior in that case. I did play around with Javac as well and found some really weird behavior. Javac only rejects referencing to the class name and constructor in the same compiler session. Once an unnamed class is compiled, it can very well be referenced from another file in another compiler session. I think the spec has to come up with some way to store this information in the .class file, so that the behavior is consistent.

**Comment by datho7561** [comment]
It seems in [the next version of the JEP](https://openjdk.org/jeps/463), you no longer need to prevent referencing the class. (unless I misunderstand the wording).

**Comment by jarthana** [comment]
> It seems in [the next version of the JEP](https://openjdk.org/jeps/463), you no longer need to prevent referencing the class. (unless I misunderstand the wording).

I still see the following. What am I missing?
`An implicit class cannot be referenced by name, so there can be no [method references](https://docs.oracle.com/javase/specs/jls/se21/html/jls-15.html#jls-15.13) to its static methods; the this keyword can still be used, however, and so can method references to instance methods.`

**Comment by datho7561** [comment]
> I still see the following. What am I missing?

Okay, I guess I am wrong

**Comment by jarthana** [comment]
This can be closed and any issues can be taken up via follow-up issues.
