### ISSUE TITLE
[sealed-classes] Incorrect unused import warning

### ISSUE THREAD

**Issue by snjeza** [eclipse-jdt/eclipse.jdt.core#1808]
The original issue: https://github.com/redhat-developer/vscode-java/issues/3446
Steps to reproduce:

- open the class
```
package foo;
import foo.X.B;
public sealed interface X permits B { 
    record B(int data) implements X {}
}
```
The JDT compiler reports
```
The import foo.X.B is never used
```

**Comment by srikanth-sankaran** [comment]
The unused import warning is a red-herring.

Real problem is this code should not compile but does:

```
public sealed interface X permits B { 
    record B(int data)  {}
}
```

**Comment by snjeza** [comment]
@srikanth-sankaran @jukzi @akurtakov I have updated https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1809

**Comment by srikanth-sankaran** [comment]
Please check with the original owner before reassigning. The proposed PR looks too much of a point fix - `if ( !(typeReference instanceof QualifiedTypeReference) && permittedType != null && permittedType.isMemberType() && permittedType.enclosingType() != null && permittedType.enclosingType().isInterface()) {` 


Is this fix required in a hurry ? I am planning a comprehensive review and rewrite of sealed classes support in the 4.32 M3 time frame. Basically the permitted classes clauses are resolved in the wrong phase.

My comment above repeated here:

The unused import warning is a red-herring.

Real problem is this code should not compile but does:

```
public sealed interface X permits B { 
    record B(int data)  {}
}
```

hold a clue to the solution.

**Comment by snjeza** [comment]
> Real problem is this code should not compile but does:

It doesn't compile with the latest PR

with the PR
![sealed](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/388609/ca7916f8-361d-4d5b-94a8-d5118dee6314)

without the PR
![sealedwithout](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/388609/64b2a4b4-7a7a-4992-9426-695ec3a9f74b)

>  I am planning a comprehensive review and rewrite of sealed classes support in the 4.32 M3 time frame. Basically the permitted classes clauses are resolved in the wrong phase.

+1

**Comment by srikanth-sankaran** [comment]
Added several review comments to the PR - If this is not super urgent, please feel free to assign it back to me. Thanks!

**Comment by srikanth-sankaran** [comment]
```
public sealed interface X permits B { 
    record B(int data)  {}
}
```

This should not compile (but does ATM with ECJ) because:

1. **6.5.1 Syntactic Classification of a Name According to Context:** 
...
A name is syntactically classified as a TypeName in these contexts
...
5. In a permits clause of a sealed class or interface declaration (§8.1.6,
§9.1.4).

So `B' is a TypeName

**2. 6.5 Determining the Meaning of a Name** 
**6.5.5.1 Simple Type Names**
If a type name consists of a single Identifier, then the identifier _must occur in the
scope of exactly one declaration of a class, interface, or type parameter_ with this
name (§6.3), or a compile-time error occurs.

So 'B' must occur in the scope of exactly one declaration of the class, interface or type parameter and refers to that  class, interface, or type parameter

**3. 6.3 Scope of a Declaration**
...
**The scope of a declaration of a member m declared in or inherited by** a class or
interface C (§8.2, §9.2) **is the entire _body_ of C**, including any nested class or interface
declarations. If C is a record class, then the scope of m additionally includes the
header of the record declaration of C.

**4. 8.1.7 Class Body and Member Declarations**
A class body may contain declarations of members of the class, that is, fields (§8.3),
methods (§8.4), classes, and interfaces (§8.5).
A class body may also contain instance initializers (§8.6), static initializers (§8.7),
and declarations of constructors (§8.8) for the class.
**ClassBody:
{ {ClassBodyDeclaration} }**


From (4) it is clear that the member record B is in scope only in the entire body of X i.e between the { and } and not in the permits clause.
