### ISSUE TITLE
[switch] Switch expression fails with instanceof + ternary operator combo

### ISSUE THREAD

**Issue by elsazac** [eclipse-jdt/eclipse.jdt.core#1820]
<img width="641" alt="image" src="https://github.com/eclipse-jdt/eclipse.jdt.core/assets/122080218/b8fe4d4a-dc1d-4e82-9003-198695dfec5d">

This compiles fine with Javac

**Comment by iloveeclipse** [comment]
@elsazac : for the sake of saving our all time, please don't report compiler bug reports **via pictures**!

One has to type everything from scratch in order to get the actual source!

Here the original code from https://github.com/eclipse-platform/eclipse.platform.ui/pull/1472#discussion_r1444428429 
```
class A {
	String method(Object element, int columnIndex) {
		return element instanceof String data ?
			switch (columnIndex) {
				case 0 -> data;
				case 1 -> data.toUpperCase();
				default -> "";
			} : "";
	}
}
```

Code doesn't compile with I20240105-1800 but compiles with Java 21 javac.

**Comment by iloveeclipse** [comment]
@srikanth-sankaran : may be something you can take a look?

**Comment by elsazac** [comment]
> @elsazac : for the sake of saving our all time, please don't report compiler bug reports via pictures!

@iloveeclipse my idea was to show the code and the associated error all in one shot, in a self explanatory manner; However I got your point an I agree to that.

**Comment by srikanth-sankaran** [comment]
> @srikanth-sankaran : may be something you can take a look?

Yes, I will.

**Comment by iloveeclipse** [comment]
Thanks @srikanth-sankaran !
