### ISSUE TITLE
Potential resource leak warning on streams from java.nio.file.Files;

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#1946]
false positives `Potential resource leak: '<unassigned Closeable value>' may not be closed` when for streams returned from java.nio.file.Files even though the stream are not resources but light weight String/Path:
```
import java.io.IOException;
import java.nio.file.Files;
import java.util.Arrays;

class A {
	A() throws Exception {
		java.util.Arrays.stream(new String[] {}); // no warning :-)
		lines(null).toList(); // no warning :-)
		java.nio.file.Files.lines(null).toList(); // stream of string -> warning :-(		
		java.nio.file.Files.walk(null, null).toList(); // stream of Path -> warning :-(
	}
	// same declaration as java.nio.file.Files.lines:
    public static java.util.stream.Stream<String> lines(java.nio.file.Path path) throws java.io.IOException {
        return null;
    }
}
```
if Potential resource leaks are enabled:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/dcc0eb68-597f-4bab-a04e-489a5109faf8)

@stephan-herrmann can you please fix?

**Comment by stephan-herrmann** [comment]
In 2013 I had direct communication with Brian Goetz on this topic, when they discussed if `Stream` should implement `AutoCloseable` and how Eclipse could distinguish closeables that do / don't *require* closing ("GC-resistant resources"?). That communication included a discussion specifically concerning class `Files`.

In that discussion we destilled the following rules (mostly using Brian's words):
* Implementing `AutoCloseable` is a tag indicating that *perhaps* closing is required to prevent leaks
  * `Stream` extends `AutoCloseable`, but generally such streams do NOT need closing
      * The only streams that do need closing are the static methods in `Files` that produce streams (`lines()`, `walk()`, etc.)

So it seems we have confirmation by Brian Goetz that those Streams do require closing, not because the String elements are GC-resistant, but because the Stream internally holds a GC-resistant resource, from which the strings are computed. That part "works as designed". 

_What we failed to discuss back then_: how are those streams actually closed. We'll have to check the actual implementation of `Files` to be certain, but my guess is that any **terminal operations** on such streams (like `toList()`) should include closing the underlying resource.

Side note: Brian mentioned the idea that JSR-308 (type annotations) could provide the right tool for specifying which types need to be checked for leaks.

Side note2: it's the same discussion, in which we also briefly touched the question, whether Java would adopt some kind of ownership model to control aliasing / sharing (a much simplified version of which is our new annotation `@Owning`). It turned out that it's a favorite topic of Brian, just he hadn't seen any approach that's sufficiently complete to be of value while not being too intrusive on Joe Java. That's a precise description of what I'm finally trying to do, reduced to the topic of resource leak detection :smile:

**Comment by jukzi** [comment]
ah, interesting, javadoc says:
```
     * @apiNote
     * This method must be used within a try-with-resources statement or similar
     * control structure to ensure that the stream's open directories are closed
     * promptly after the stream's operations have completed.
```
indeed this works:
```
		try (Stream<String> lines = java.nio.file.Files.lines(null)){ //allowed
			lines.filter(c->true);
		}
		try (Stream<String> lines = java.nio.file.Files.lines(null).filter(c->true)){ //not allowed, warning
			;
		}

```

**Comment by jukzi** [comment]
we will have to fix JDTs  Files.walk usage in
org.eclipse.jdt.internal.compiler.util.CtSym.getCachedReleasePaths(String)
org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.deleteSourceFiles(File)
