### ISSUE TITLE
Wrong compilation error reported when multi type catch block references visible method from invisible type

### ISSUE THREAD

**Issue by lukaseder** [eclipse-jdt/eclipse.jdt.core#198]
To reproduce, try to compile this e.g. with Java 17

```java
package p;

import p.Exceptions.*;

class Exceptions {
    private static class E extends Exception {
        void m() {}
    }
    static class E1 extends E {}
    static class E2 extends E {}
}

public class Test {
    static void m() throws E1, E2 {}
    public static void main(String[] args) {
        try {
            m();
        }
        catch (E1 | E2 e) {
            e.m(); // This doesn't compile
        }
    }
}
```

The compilation error on the `e.m()` call is:

> The type Exceptions.E is not visible

But the type doesn't have to be visible for the method to be visible. `javac` compiles this just fine.

**Comment by lukaseder** [comment]
As a workaround, using separate catch blocks compiles just fine:

```java
try {
    m();
}
catch (E1 e) {
    e.m();
}
catch (E2 e) {
    e.m();
}
```

**Comment by jvasileff** [comment]
I believe the ecj error is correct, and that the bug is with javac 17. Copied from my comment on the corresponding IJ bug report:

------

I believe the sample code is invalid. It succeeds at runtime on Java 17 only because there is no such thing as a `private` class on the JVM; the `private` modifier only serves a purpose at compile time.

The compile time error produced by javac 11 appears to be correct:

> error: E.m() is defined in an inaccessible class or interface

because, within the catch block, the type of `e` is `Exceptions.E` per the LUB algorithm in "4.10.4. Least Upper Bound". And, per "6.6. Access Control", `Exceptions.E` should not be accessible outside of `Exceptions`. The members of `Exceptions.E` should be unavailable.

In "6.6. Access Control":

> Otherwise, the member or constructor is declared private. Access is permitted only when the access occurs from within the body of the top level class or interface that encloses the declaration of the member or constructor.

-------

This becomes a problem at runtime if the example is changed such that it doesn't exploit differences in the Java and JVM accessibility models. If `Exceptions` is defined in another package, a `java.lang.IllegalAccessError` is produced at runtime.

p/Exceptions.java
```java
public class Exceptions {
    private static class E extends Exception {
        public void m() { }
    }
    public static class E1 extends E {}
    public static class E2 extends E {}
}
```

q/Test.java
```java
package q;

import p.Exceptions;
import p.Exceptions.*;

public class Test {
    public static void main(String[] args) {
        try {
            if (false) { throw new E2(); }
            throw new E1();
        } catch (E1 | E2 e) {
            e.m(); // javac 11: ...defined in an inaccessible class...
        }
    }
}
```

Results in:

```
% javac p/Exceptions.java q/Test.java && java q.Test
Exception in thread "main" java.lang.IllegalAccessError: failed to access class p.Exceptions$E from class q.Test (p.Exceptions$E an
        at q.Test.main(Test.java:12)
```

**Comment by jvasileff** [comment]
> Can you link this bug report here? 

https://youtrack.jetbrains.com/issue/IDEA-297529

**Comment by trancexpress** [comment]
Alright, thanks.

I've asked on serviceability-dev@openjdk.java.net for clarification. The runtime exception is an argument enough for me, to have a compile error. Though I've not checked the spec paragraphs you've mentioned. Lets see what OpenJDK maintainers say.

**Comment by trancexpress** [comment]
OK, a JDK bug was opened: https://bugs.openjdk.org/browse/JDK-8305649

Closing this as "not Eclipse".

**Comment by srikanth-sankaran** [comment]
> OK, a JDK bug was opened: https://bugs.openjdk.org/browse/JDK-8305649
> 
> Closing this as "not Eclipse".
> 
> Thanks for the analysis @jvasileff .

@trancexpress - your comment says "Closing as not eclipse" but the issue is still open ? Intentional ??

**Comment by trancexpress** [comment]
Sorry I probably forgot to use the special GitHub button.
