### ISSUE TITLE
[23] JEP 482: Flexible Constructor Bodies (Second Preview)

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2472]
ref: https://openjdk.org/jeps/482

Summary
In constructors in the Java programming language, allow statements to appear before an explicit constructor invocation, i.e., super(..) or this(..). The statements cannot reference the instance under construction, but they can initialize its fields. Initializing fields before invoking another constructor makes a class more reliable when methods are overridden. This is a [preview language feature](https://openjdk.org/jeps/12).

Spec changes at: https://cr.openjdk.org/~gbierman/jep482/latest/

Refere https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1637 for the Java 22 support issue of its predecessor JEP 447

**Comment by stephan-herrmann** [comment]
Collecting input from other issues:
* post-hoc review comments in #2063
* #2467 
* #2464 
  * based on clarification via #2469

**Comment by stephan-herrmann** [comment]
@mpalat  from readings Dan's clarification on the list I envision the main implementation change to affect `Statement.isPreConstructorContext`, where I believe a single boolean no longer suffices, since we need to answer if we're in an early construction context _regarding a given class_. This is needed to allow access to `SomeFarOuter.this` even when we are in an early construction context regarding a local / anonymous class.

Let me suggest to refactor this into smth like `Scope.isInEarlyConstructionContextOf(ReferenceBinding targetClass)`, where `targetClass` is a class whose `this` or some member we're about to access. Each `ClassScope` would store the corresponding flag, and the above method would delegate to parents until `Scope.enclosingSourceType()` equals `targetClass` (or no more parents). OK?

**Comment by stephan-herrmann** [comment]
During this issue we might add the test from https://bugs.eclipse.org/564263

**Comment by stephan-herrmann** [comment]
@mpalat  have you started any work for this JEP?

Given the complexitity of this issue and my [discussion on amber-spec-experts](https://mail.openjdk.org/pipermail/amber-spec-experts/2024-May/004135.html), I could think of making this my next priority, i.e., get my hands dirty implementing.

**Comment by stephan-herrmann** [comment]
PR Draft 01: https://cr.openjdk.org/~iris/se/23/spec/pr/java-se-23-pr-spec-01/specs/flexible-constructor-bodies-jls.html

**Comment by mpalat** [comment]
> @mpalat have you started any work for this JEP?
@stephan-herrmann - not yet as I am busy with primitive in patterns and was planning to schedule it only after that.

> Given the complexitity of this issue and my [discussion on amber-spec-experts](https://mail.openjdk.org/pipermail/amber-spec-experts/2024-May/004135.html), I could think of making this my next priority, i.e., get my hands dirty implementing.

Definitely yes, please take it up. Thanks.
