### ISSUE TITLE
[23] JEP 477: Implicitly Declared Classes and Instance Main Methods (Third Preview)

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2474]
ref: https://openjdk.org/jeps/477

Summary
Evolve the Java programming language so that beginners can write their first programs without needing to understand language features designed for large programs. Far from using a separate dialect of the language, beginners can write streamlined declarations for single-class programs and then seamlessly expand their programs to use more advanced features as their skills grow. Experienced developers can likewise enjoy writing small programs succinctly, without the need for constructs intended for programming in the large. This is a [preview language feature](https://openjdk.org/jeps/12).

Latest Spec Changes : https://cr.openjdk.org/~gbierman/jep477/latest/

Predecessor: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1640

**Comment by jarthana** [comment]
I see two major changes since the last iteration:
`Every simple compilation unit implicitly imports on demand every public class or interface declared in all the packages exported by the predefined module java.base, as if the declaration import module java.base; appeared at the beginning of each simple compilation unit ([7.5.5](https://cr.openjdk.org/~gbierman/jep477/jep477-20240507/specs/import-module-declarations-jls.html#jls-7.5.5)). As a result, the names of all those classes and interfaces are available as simple names in every simple compilation unit.`
 and 
`Every simple compilation unit implicitly imports all the static members from the class java.io.IO, as if the declaration import static java.io.IO.*; appeared at the beginning of the simple compilation unit immediately after the declaration that imports module java.base;. As a result, the names of all those static members are available as simple names in every simple compilation unit.`

Probably in a first, there is a dependency between preview features. This one depends on #2383

**Comment by jarthana** [comment]
This can be closed now.
