### ISSUE TITLE
Multi-Release JAR is not recognized as such

### ISSUE THREAD

**Issue by eitan-rosenberg** [eclipse-jdt/eclipse.jdt.core#2495]
Recently, I update com.google.code.gson:gson to version 2.11.0 from version 2.10.1.

The project use module-info.java and use "requires com.google.gson;"

gson-2.11.0.jar is a Multi-Release JAR and the module declaration is at META-INF/versions/9/module-info.class

I open [an issue ](https://github.com/google/gson/issues/2679) and it got the full details.
Also included in that issue a small project to demonstrate the problem.(https://github.com/google/gson/files/15412480/ModuleTest.zip)

**When using pure maven build "mvn clean test" it is compiled successfully.
Also I can run it using  "mvn compile exec:java -Dexec.mainClass="main.Main"" .**

I use: 
M2E Maven Integration for Eclipse Core 2.6.0.20240220-1109
Eclipse 2024-03 (4.31)
Java openjdk version "22.0.1" 2024-04-16

Thanks in advance for any response.

**Comment by eitan-rosenberg** [comment]
Hi there...
Anyone at home ?

**Comment by howlger** [comment]
@eitan-rosenberg Please reopen this issue as it still exists.

Steps to reproduce this issue:
1. Create a new Java project name `Sample` of Java 9 or higher with the option _Create module-info.java_
2. Add the [`com.networknt:json-schema-validator:1.4.3` JAR](https://repo1.maven.org/maven2/com/networknt/json-schema-validator/1.4.3/json-schema-validator-1.4.3.jar) to the build path
3. Edit the `module-info.java` as follows:
	```java
	module Sample {
	
		requires json.schema.validator; // module name mistakenly derived from the file name "json-schema-validator-1.4.3.jar"
	
		// ... instead of from "META-INF/versions/9/module-info.class" as follows:
		requires com.networknt.schema;
		//       ~~~~~~~~~~~~~~~~~~~~
		//       com.networknt.schema cannot be resolved to a module
	
	}
	```

Expected: `requires json.schema.validator;` should give an error and `requires com.networknt.schema;` should work instead.

See also: [Stack Overflow question _"JsonSchemaValidator module name is confused Maven vs Eclipse"_](https://stackoverflow.com/q/78721721/6505250)

**Comment by Marcono1234** [comment]
It seems this is related to the moditect-maven-plugin. For Gson and json-schema-validator it looks like this issue started occurring when they updated moditect-maven-plugin to 1.2.0.Final (for Gson 2.10.1 → 2.11.0; for json-schema-validator 1.4.0 → 1.4.1).

I am not completely sure where exactly the issue is within jdt.core and if there are multiple classes affected (please double check!), but I could at least find one location:
https://github.com/eclipse-jdt/eclipse.jdt.core/blob/ed787f542d5509ba226f0b8b06982d61e81b4622/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/builder/ClasspathMultiReleaseJar.java#L83-L85

Here is an example for testing this:
```java
public static void main(String[] args) throws Exception {
    System.out.println(getModuleName("gson-2.10.1.jar"));
    System.out.println(getModuleName("gson-2.11.0.jar"));

    System.out.println(getModuleName("json-schema-validator-1.4.0.jar"));
    System.out.println(getModuleName("json-schema-validator-1.4.1.jar"));
}

static String getModuleName(String path) throws Exception {
    AccessRuleSet accessRuleSet = new AccessRuleSet(new AccessRule[0], AccessRestriction.LIBRARY, "test");
    ClasspathJar classpathJar = new ClasspathMultiReleaseJar(new ZipFile(path), accessRuleSet, true, "9");
    // Initialize module information
    new ModulePathEntry(new Path(path), classpathJar);
    return new String(classpathJar.getModule().name());
}
```
(tested with `org.eclipse.jdt:org.eclipse.jdt.core:3.38.0`)

The code in `ClasspathMultiReleaseJar` assumes that for multi-release JARs a (directory) entry exists, e.g. `META-INF/versions/9/`. However, https://github.com/moditect/moditect/pull/230 (accidentally?) changed the JAR modification code to not generate that entry anymore, but only the `META-INF/versions/9/module-info.class` entry.

It is not completely clear if that directory entry is required. The [JAR specification](https://docs.oracle.com/en/java/javase/21/docs/specs/jar/jar.html#multi-release-jar-files) talks about the "directory" but it does not explicitly say that this directory must exist as ZIP entry.

`javac` does not seem to care whether the ZIP directory entry exists or not.

**Comment by Marcono1234** [comment]
As side note: This only affects JDT within the Eclipse IDE. The ECJ batch compiler does not properly support modular multi-release JARs at all, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=577790 and #61.

**Comment by gv2011** [comment]
Probably related: [Bugzilla – Bug 534624 Support module-info.java in multi-release JAR files](https://bugs.eclipse.org/bugs/show_bug.cgi?id=534624)

I have the same problem AndreasWBartels described.

**Comment by nlisker** [comment]
See also https://github.com/FasterXML/jackson-databind/issues/4727 for the complaints in Jackson, which is also related to Moditech. The conclusion there is that it's an Eclipse issue, but they have worked around it by downgrading their Moditech version while waiting for an Eclipse-side fix.

**Comment by wglas85** [comment]
I have more affected libraries, which contain  `META-INF/versions/9/module-info.class`:
```
      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-fileupload2-jakarta-servlet6</artifactId>
        <version>2.0.0-M4</version>
      </dependency>
      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-fileupload2-core</artifactId>
        <version>2.0.0-M4</version>
      </dependency>
```

Please fix this issue, there are supposedly much more affected  libraries out there and it is simply a non spec-compliant behavior by eclipse jdt.

TIA, Wolfgang

**Comment by robtimus** [comment]
I encountered this issue today with Jackson core 3.0.3 and Eclipse 2025-12. Interestingly enough, Jackson uses the latest version of Moditect which includes the parent folders. When I check the contents of the JAR file I see that all parent folders are present:
```
$ jar tf jackson-core-3.0.3.jar | grep META-INF/versions
META-INF/
META-INF/MANIFEST.MF
...
META-INF/versions/
META-INF/versions/17/
META-INF/versions/17/module-info.class
...
```
However, Eclipse still refuses to recognize the module.

**Comment by Marcono1234** [comment]
> I encountered this issue today with Jackson core 3.0.3 and Eclipse 2025-12

Hmm, I cannot reproduce this, for me it works fine with Maven and `requires tools.jackson.core;` in the `module-info.java` of my project. You are using Java >= 17 for building[^1], right (e.g. `<maven.compiler.release>17</maven.compiler.release>`)?
In case you are using Maven, maybe also try right clicking the project and using "Maven" > "Update Project...".

In case your project is a plain Eclipse "Java Project" (not using Maven or Gradle), make sure the `jackson-core-3.0.3.jar` is added to the "Modulepath" and not the "Classpath" of the project libraries.

[^1]: Because Jackson requires Java >= 17 since version 3.x

**Comment by robtimus** [comment]
I was using Java 11 instead of 17. Changing that fixed the issue. And that actually makes sense, since Jackson core's `module.info.class` is located in `META-INF/versions/17`.

**Comment by vsilaev** [comment]
What helps for me is the following:
1. `META-INF/MANIFEST.MF` should contain an entry with the `Java-Version: 8`, or any base Java version for the JAR
2. `META-INF/versions/9/module-info.class` exists, or any version ABOVE base Java version for the JAR

The crucial point was to define Java-Version inside MANIFEST.MF, otherwise `module-info` was not considered as existed.

**Comment by stephan-herrmann** [comment]
I found this issue only now. If someone provides a self-contained zipped Eclipse project that demonstrates the problem without the use of additional build tools, then I might have a look into it.

**Comment by Speiger** [comment]
@stephan-herrmann if you import lwjgl3 core jar (a very tiny project) into eclipse using maven/gradle and try to open classes which are version specific then it will fail to find it and the code editor can not find it either.

SegmentStack is a new class that is affected.
Link: https://www.lwjgl.org/customize
Set preset to none and select gradle/maven it will make you a script you can insert into the appropriate project.
Stable/Early Access doesn't matter

Code Snippets to make it easier.

<details>
<summary>Gradle</summary>
<p>


```groovy
project.ext.lwjglVersion = "3.4.1"
project.ext.lwjglNatives = "natives-windows"

repositories {
	mavenCentral()
}

dependencies {
	implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")

	implementation "org.lwjgl:lwjgl"
	implementation "org.lwjgl:lwjgl::$lwjglNatives"
}
```

</p>
</details>

<details>
<summary>Maven</summary>
<p>

```xml
<properties>
	<lwjgl.version>3.4.1</lwjgl.version>
	<lwjgl.natives>natives-windows</lwjgl.natives>
</properties>

<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.lwjgl</groupId>
			<artifactId>lwjgl-bom</artifactId>
			<version>${lwjgl.version}</version>
			<scope>import</scope>
			<type>pom</type>
		</dependency>
	</dependencies>
</dependencyManagement>

<dependencies>
	<dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl</artifactId></dependency>
	<dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl</artifactId><classifier>${lwjgl.natives}</classifier></dependency>
</dependencies>
```

</p>
</details>

Edit: 
They also have direct jar downloads.

**Comment by stephan-herrmann** [comment]
> if you import lwjgl3 core jar (a very tiny project) into eclipse using maven/gradle

Thanks, that's close but no cigar. Any need to fiddle with maven/gradle on our side decreases the chances that we/I find the time for analyzing. Sorry.

>  They also have direct jar downloads.

So, the following would help greatly: create a small eclipse project that depends on an affected jar file, upload a full zip of that project. It's OK if at that point it fails to compile. Then tell us where to download that jar file, and from there we will take over.

BTW, any dependency on windows native artifacts would be a blocker for me as I'm on linux :)

**Comment by Speiger** [comment]
@stephan-herrmann 
Here is a eclipse project without gradle or Maven that shows how multijars are not supported.
Following things are required:
- JDK 25
- The Project Itself (sry had to make the joke)
[MultiJarTest.zip](https://github.com/user-attachments/files/28274736/MultiJarTest.zip)

I provided both windows and Linux Native Bindings and setup everything so it will compile.
Only thing i threw out was module stuff as it was hindering compiling stuff (still new to it)

In there you will find a Main.java which has 2 try blocks the first one should compile just fine if you setup everything correctly.
The second try block will simply not work because the class can not be found as it is only accessible through the META_INF/versions/25 area.

LWJGL3 uses versions to add support to newer features such as javas FFM api while keeping support for the Unsafe backend for older versions.

Hope this helps.

Edit:
Here is the example of the "working" failure state
<img width="678" height="271" alt="Image" src="https://github.com/user-attachments/assets/c82c377f-0690-4a75-b603-7567a51ad3fc" />

**Comment by robtimus** [comment]
Disclaimer: I am not part of the Eclipse team.

According to [JEP 238](https://openjdk.org/jeps/238), a multi-release JAR file is created to "allow multiple, Java-release-specific versions of class files to coexist in a single archive." The entire description does not mention anything about _adding_ classes. While technically it's allowed if they are necessary for implementing the release-specific class files, they are _not_ part of the public API. Apparently they actually can be used in Java 25 (not Java 17), with lwjgl on either the class path or on the module path, but relying on them is bad practice.

**Comment by Speiger** [comment]
@robtimus yeah this exact case was brought up in the LWJGL Discord as well 1 hour before you posted your comment.

I am just a viewer in this scenario.
Not sure though who is at fault though.

**Comment by stephan-herrmann** [comment]
Thanks to the self contained example I had just started to debug this, and found a location that scans the jar mainly interested in finding version specific *overrides*. This is very much related to @robtimus' quote of JEP 238.

When maven build succeeds should we read this as confirmation that javac accepts this structure?

**Comment by Speiger** [comment]
@stephan-herrmann 
Here is the thing the only thing i realized first is: Ok this new class is not callable and the decompiling plugin isn't capable of seeing the sourcecode of that new class.

Another thing i just right now realized is: That the changes/replacements the version provides are not applied/visible in eclipse.
When you open the sourcecode the jdk8 version code is displayed when you open the source with eclipse.

So i can't really guess which code applies.
The logs tell me: Unsafe is not called but the code displayed is the Unsafe implementation.

So which is the truth?

Overall, i don't know exactly what is broken with eclipse MultiJar Support, @Spasi might be a lot more knowledgeable here, only thing i know it doesn't show me exactly what happens in the backend.

I just found this issue 13 hours after you told: If someone has an example i will debug it...

**Comment by robtimus** [comment]
The provided code runs on Java 25:
* with class path:
  ```
  java -cp "jars/*" src/multijarTest/Main.java
  ```
* with module path
  ```
  # turn into a module
  echo "module test { requires org.lwjgl; }" > src/module-info.java
  # fix linux vs windows conflict
  mv jars/lwjgl-natives-windows.jar jars/lwjgl-natives-windows.jar.disabled
  java --module-path jars/ src/multijarTest/Main.java
  ```

**Comment by stephan-herrmann** [comment]
Hold on, I think I found a simple bug in Commit b7a3b808 ...

**Comment by Marcono1234** [comment]
So far the main aspect of this issue was handling of multi-release `module-info.class` files. JEP 238 explicitly mentions this as supported use case:
> A multi-release modular need not have a module descriptor at the located root. In this respect a module descriptor would be treated no differently to any other class or resource file. This can ensure that, for example, only Java 8 versioned classes are present in the root area while Java 9 versioned classes (including the module descriptor) are present in the 9 versioned area.

An indeed this is what many libraries (such as the above mentioned Gson, Jackson, ...) do respectively did in the past to not break Java 8 / Android tooling while at the same time offering a module descriptor for Java 9+ consumers of the library.
And there this Eclipse issue becomes noticeable during compile time because Eclipse fails to find the third-party modules (which are multi-release JARs) your own `module-info.java` refers to.
If you want I can provide a minimal example for this as well.

Though the other issues you mentioned above (source lookup, ...) might be other aspects of the same underlying issue.

@stephan-herrmann, in case you hadn't see it, a while ago I had a rough look at the Eclipse code and described my findings in https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2495#issuecomment-2254297050 and https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2495#issuecomment-2256565641.

**Comment by stephan-herrmann** [comment]
Meanwhile this issue has accumulated many comments that may or may not be directly related.

Let's try to take stock:
* [original problem](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2495#issue-2316843189)
   * needed maven to reproduce, maybe that's why nobody in JDT immediately jumped at it
   * was reported to be resolved by the reporter in [this comment](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2495#issuecomment-2173604217) ✔️ 
* [report](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2495#issuecomment-2214835656) by @howlger 
   * bug can still be reproduced (I found description for a self-contained repro only now) ❌ 
* when I read about moditect-maven-plugin I skipped reading because I had no idea how that would have an impact on JDT ;-P
   * will have a closer look at that comment later. ⌛ 
* when another problem was captured in a self-contained way in [this comment](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2495#issuecomment-4546144148) I immediately got to it and pushed [#5038](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/5083) as a fix for it. ✔️

**Comment by stephan-herrmann** [comment]
>  * [report](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2495#issuecomment-2214835656) by [@howlger](https://github.com/howlger)
>      * bug can still be reproduced (I found description for a self-contained repro only now) ❌

I made a quick experiment whether it makes a difference if directory `META-INF/versions/9/` is explicitly present in the jar: for @howlger's example it makes no difference.

I'm not surprised to see that `module-info.class` needs some special attention.

**Comment by Marcono1234** [comment]
Here is a minimal demo project for `module-info.class` handling: [multi-release-test.zip](https://github.com/user-attachments/files/28343184/multi-release-test.zip)

Tested with Eclipse IDE for Java Developers 2026-03. Contains both a library with and without additional `META-INF/versions/` and `META-INF/versions/9/` JAR entries. For the variant without those entries Eclipse does not recognize the module declaration.

**Comment by stephan-herrmann** [comment]
> Here is a minimal demo project for `module-info.class` handling: [multi-release-test.zip](https://github.com/user-attachments/files/28343184/multi-release-test.zip)
> 
> Tested with Eclipse IDE for Java Developers 2026-03. Contains both a library with and without additional `META-INF/versions/` and `META-INF/versions/9/` JAR entries. For the variant without those entries Eclipse does not recognize the module declaration.

Thanks a lot. This contradicts my previous observation, but with this example I can reproduce your observations.

This is more than one or two bugs. I'm on it.

**Comment by stephan-herrmann** [comment]
Some code locations that explicitly check for existence of directory entries in a jar:
* org.eclipse.jdt.internal.core.builder.ClasspathMultiReleaseJar.initializeVersions(ZipFile)
   * looks for `META-INF/versions/9/` ... to detect that specific class files for that version might be present
* org.eclipse.jdt.internal.core.JarPackageFragmentRoot.computeChildren(OpenableElementInfo, IResource)
   * same as above, **and**
   * doesn't even look for any specific versions if entry `META-INF/versions/`  is missing.

This very much looks like significant optimization, as otherwise we'd have to always read each jar fully to retrieve the desired information.

Some options:
1. ignore performance issues and always read all jar entries to figure out its shape
2. ignore problems with jars without explicit directory entries
3. use an API that is better suitable than ZipFile in terms of performant scanning
4. use a cascaded approach to read as much as needed
   * extra scrutiny only if the jar is on the module path
      * then read the manifest and proceed only if we find `Multi-Release:true`
         * then look at least for `META-INF/versions/n/module-info.class` for _n_ in relevant versions

(1) is not a good option. For (2) we'd need some understanding of why/when directory-less jars occur? Are those just an accident or are these to be expected systematically?

Regarding (3): @jarthana I see that in some distant past you had been going back and forth between `ZipFile` API, and corresponding API from `java.nio.zipfs`. From what I saw the last decision to stick with `ZipFile` was motivated by concurrency issues. Would you see a chance that OTOH the `java.nio.zipfs` API would allow for performant scanning even in the case of absent directory entries?

Route (4) might be the safest for now, if we find good answers to the following:
* is reading and parsing each jar manifest tolerable for projects with a large number of jar dependencies?
* the above solves the full scan issue only for versions with `module-info.class` present
   * has anybody observed the same problem regarding absent directory entries also in cases where no `module-info.class` was involed?
   * if needed, is it tolerable to do a full scan for each jar that is known to be multi-release?

**Comment by stephan-herrmann** [comment]
> extra scrutiny only if the jar is on the module path

I guess this was premature, multi-release jars should work also on the classpath

**Comment by stephan-herrmann** [comment]
> has anybody observed the same problem regarding absent directory entries also in cases where no module-info.class was involed?

I can observe that using the unit test from #5083 with a jar file crafted without directory entries (have to list class files explicitly when creating the jar).

**Comment by stephan-herrmann** [comment]
With the previous two clarifications, the cascaded approach would have only one level of saving:
* for **each jar** read the manifest and check for `Multi-Release: true`
  * only if found, fully scan that jar for `META-INF/versions/*/**`

This would quite certainly impose a performance penalty, right?

**Comment by Speiger** [comment]
@stephan-herrmann 
> This would quite certainly impose a performance penalty, right?

There comes 2 things to mind as well.
A result cache and a option to manually disable the support for multijars for specific libraries.

Those two could also help with performance penalties.

**Comment by stephan-herrmann** [comment]
> > * [report](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2495#issuecomment-2214835656) by [@howlger](https://github.com/howlger)
> >   
> >    * bug can still be reproduced (I found description for a self-contained repro only now) ❌
> 
> I made a quick experiment whether it makes a difference if directory `META-INF/versions/9/` is explicitly present in the jar: for [@howlger](https://github.com/howlger)'s example it makes no difference.
> 
> I'm not surprised to see that `module-info.class` needs some special attention.

Update on this case:
* to fix the provided jar both these directories need to be added:
   * `META-INF/versions/`
   * `META-INF/versions/9/`
 
With those additions, `module-info.class` is correctly recognized.

**Comment by stephan-herrmann** [comment]
Before deciding to abandon the current strategy in favor of full jar scans, or other big changes, I'd like to understand why some jars have explicit directory entries and others don't.
* in the case of `moditect-maven-plugin` it seems omitting directories was unintentional and has meanwhile been reverted, right?
* what other tools produce directory-less jars?
   * always? or since when?
   * intentionally?
* is this a wide spread issue, or affecting only very few select jar files on the net?

I searched a bit for a specification (zip or jar file format) that would clarify, what is / isn't legal, but found nothing applicable.

**Comment by iloveeclipse** [comment]
@mehmet-karaman, I believe you should have the pointer to the zip specs.
If I remember right, directory entries are optional in zip specification, so some tools write them, some not, depending on given options.

**Comment by Marcono1234** [comment]
(The following is only in the context of the `module-info.class` issue; it might not apply to the other multi-release JAR issues mentioned in the previous comments.)

> in the case of `moditect-maven-plugin` it seems omitting directories was unintentional and has meanwhile been reverted, right?

Unintentional I assume yes, and has been fixed: https://github.com/moditect/moditect/pull/260
But I don't think the fact that they merged the fix means that they admit it was ModiTect which was behaving incorrectly. As you mentioned, it is not clear if those JAR directory entries are required by any specification or not.

> is this a wide spread issue, or affecting only very few select jar files on the net?

Based on the previous comments here, at least certain versions of Gson, Jackson and json-schema-validator were affected. ModiTect is used by quite a few projects which want to target Java 8 but at the same time include a module descriptor for Java 9+ users.

So maybe not a "wide spread issue", but I think it is plausible that other libraries using ModiTect were affected as well (or still are, if they haven't updated their plugin dependencies yet). But maybe they have not traced it back to Eclipse or ModiTect yet, or they don't have as many users as Gson or Jackson. And it appears to be only noticeable for users who have their own `module-info.java` in their project (which depends on the library multi-release module descriptor), which further reduces the chance of it being noticed and reported.

**Comment by trancexpress** [comment]
The new test seems to fail during I-build, maybe sporadically. I've opened: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/5094

**Comment by mehmet-karaman** [comment]
@iloveeclipse Paths in ZIP files are optional. It is the responsibility of the implementer to validate or handle path information appropriately. A ZIP file itself does not enforce any rules about path validity, nor does it ensure that paths are compatible with the target operating system.

See: https://commons.apache.org/proper/commons-compress/examples.html, especially the section “Entry Names”. (The standard Java ZIP implementation behaves similarly.)

**Comment by laeubi** [comment]
> With the previous two clarifications, the cascaded approach would have only one level of saving:
> 
>     * for **each jar** read the manifest and check for `Multi-Release: true`
>       
>       * only if found, fully scan that jar for `META-INF/versions/*/**`
> 

This sounds correct to me according to MR specification (and how MR compilation support is implemented.

> This would quite certainly impose a performance penalty, right?

Correctness comes before performance. I also don't think it would be useful to allow disable it because it will lead to different behavior on runtime what can be surprising.

**Comment by stephan-herrmann** [comment]
> [@iloveeclipse](https://github.com/iloveeclipse) Paths in ZIP files are optional. It is the responsibility of the implementer to validate or handle path information appropriately. A ZIP file itself does not enforce any rules about path validity, nor does it ensure that paths are compatible with the target operating system.
> 
> See: https://commons.apache.org/proper/commons-compress/examples.html, especially the section “Entry Names”. (The standard Java ZIP implementation behaves similarly.)

Thanks Mehmet for your research!

As a result we cannot simply shrug off this problem, as I had secretly hoped :)

**Comment by stephan-herrmann** [comment]
> > With the previous two clarifications, the cascaded approach would have only one level of saving:
> > * for **each jar** read the manifest and check for `Multi-Release: true`
> >   * only if found, fully scan that jar for `META-INF/versions/*/**`
> 
> This sounds correct to me according to MR specification (and how MR compilation support is implemented.

I intend to just add one more shortcut: if `META-INF/versions/` is present, we probably don't need to read and parse the manifest, but may directly assume an MR jar, right? :)
 
> > This would quite certainly impose a performance penalty, right?
> 
> Correctness comes before performance. I also don't think it would be useful to allow disable it because it will lead to different behavior on runtime what can be surprising.

Now that we have confirmation that such directory-less MR jars are legal, I certainly agree.

**Comment by iloveeclipse** [comment]
> I intend to just add one more shortcut: if `META-INF/versions/` is present, we probably don't need to read and parse the manifest, but may directly assume an MR jar, right? :)

Correct. So in the zip file visitor one can stop scanning entries once one sees one starting with this path

**Comment by laeubi** [comment]
> if `META-INF/versions/` is present, we probably don't need to read and parse the manifest, but may directly assume an MR jar, right? :)

Wrong ... per MR specification only the manifest attribute matter is MR is enabled or not even though its of course unlikely. So one *might* use this as an indication that the manifest must be inspected (if it helps). 

So if there is **no entry** with `META-INF/versions/` then it can be a MR-jar per specification but as no versions are present the observable result it the same as if it where not one.

See https://openjdk.org/jeps/238

> A multi-release JAR ("MRJAR") will contain the main attribute:
> `Multi-Release: true`
> declared in the main section of the JAR MANIFEST.MF

The specification nowhere mentions that having a version folder (entry) might be enough. As even the automatic module name is in the manifest I assume the manifest has to be parse anyways.

**Comment by iloveeclipse** [comment]
Note: I'm not sure what exactly Stephan wanted to optimize, my previous comment was related to jar traversing.

**Comment by laeubi** [comment]
I'm not 100% sure either... but I assumed we are talking about [ClasspathMultiReleaseJar](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/builder/ClasspathMultiReleaseJar.java) what currently tries to find all supported versions, then returns the highest where it finds a module-info based on the assumption there is a path with the name `META-INF/versions/<x>` what is wrong.

Instead it must be iterating from `compliance` (what is a bit misleading naming but anyways) down to version 9 and return the first matching module descriptor, I would assume that iterating all entries might be fast given the zip file is already open but might be wrong. Strictly speaking one has to first check if it is a MR jar by looking at the manifest (but possibly delay it until a MR entry is actually found).

**Comment by stephan-herrmann** [comment]
> Note: I'm not sure what exactly Stephan wanted to optimize,

> I'm not 100% sure either...

My plan still was a moving target at that point 😄 . #5157 chooses correctness over performance.
