### ISSUE TITLE
Issue with code fence > 3 in markdown comment

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#3004]
Inspecting the code change in #2989 it seems to break handling of code fences of four or more characters. Consider the following contrived example:

```java
	/// ````
	/// ```
	/// @param is not a tag here because this is nested literal *markdown*
	/// ```
	/// ````
	void m() {}
```

Here we should recognize a code block delimited by four backticks, where three backticks don't suffice to terminate the block. As a result `@param` should *not* be interpreted as a javadoc tag, but as literal text.

The problem relates to field `org.eclipse.jdt.internal.compiler.parser.MarkdownCommentHelper.fenceLength` no longer being increased to a value greater than 3.

**Comment by stephan-herrmann** [comment]
@jarthana fyi.

**Comment by jarthana** [comment]
Stephan, admittedly I spent little time studying this code before my last fix. But now I have been staring at this code for a while now and wondering how this works. I see that the whole markdown helper comes into the picture only after the first tag because that's what we considered to be the realStart in AbsCommentParser#commentParse(). So, I don't understand how the detection of fencing end works at all, especially in this case, since we don't seem to be studying the opening fencing at all.

**Comment by stephan-herrmann** [comment]
> Stephan, admittedly I spent little time studying this code before my last fix. But now I have been staring at this code for a while now and wondering how this works. I see that the whole markdown helper comes into the picture only after the first tag because that's what we considered to be the realStart in AbsCommentParser#commentParse(). So, I don't understand how the detection of fencing end works at all, especially in this case, since we don't seem to be studying the opening fencing at all.

Coming back here after my review comments: right, perhaps in markdown mode we should just completely ignore `firstTagPosition`.  In that case I only wonder what `linePtr` should be initialized to?

**Comment by jarthana** [comment]
> Coming back here after my review comments: right, perhaps in markdown mode we should just completely ignore `firstTagPosition`. In that case I only wonder what `linePtr` should be initialized to?

Good point. I think this should be set accordingly. Will add this change.
