### ISSUE TITLE
Javax.sound package not accessible

### ISSUE THREAD

**Issue by lambdacore12** [eclipse-jdt/eclipse.jdt.core#3008]
Hello. I just created my first Java project and I get the error "The package javax.sound is not accessible."

I have looked throughout the internet and added "requires java.desktop" in module-info.java, but to no avail.

I am using the latest ECLIPSE IDE 2024-09.

![image](https://github.com/user-attachments/assets/46636d50-86d0-44ad-a41a-ba46fa989649)

**Comment by stephan-herrmann** [comment]
The module `java.desktop` does not export a package named `javax.sound`, see its  `module-info.java`:
```java
module java.desktop {
    ...
    exports javax.sound.midi;
    exports javax.sound.midi.spi;
    exports javax.sound.sampled;
    exports javax.sound.sampled.spi;
    ...
```

This information will suffice to fix your code.

If you want to dig deeper you may want to know whether or not package `javax.sound` actually exists.

Part of JLS require that some class _declares_ the package like this:
```java
package javax.sound;
public class X ...
```

Such a class X does not exist, and hence it would be OK to reason that package `javax.sound` doesn't exist at all.

Other parts of JLS, however, seem to imply that a package like `javax.sound.midi` has a parent package `javax.sound`. That's the reason why ecj complains "not accessible" rather than "does not exist".

**Comment by lambdacore12** [comment]
Thank you!
