### ISSUE TITLE
Stackoverflow protection during recursive call

### ISSUE THREAD

**Issue by robstryker** [eclipse-jdt/eclipse.jdt.core#3213]
SourceTypeBinding.methods() and SourceTypeBinding.resolveTypesFor(MethodBinding etc) both make use of 'scope'. If the binding has already been cleaned up, scope is null, and these methods are not null safe. 

Furthermore, getMethods(char[] selector) has a recursive call with no check to avoid a recursive stack overflow. 

Details: 

We're doing some unique things with JDT, and we've run into an NPE, and, after fixing that, a stack overflow, in some unique situations. 

I believe that, upon review, you'll see the patch is safe and unlikely to cause any issues. As for the exact cause, I haven't completely figured it out. An ASTParser parses a file, creates the bindings, and then cleans up. For some reason, a later call to get a specific binding ends up looking for the scope object, which has been cleaned up already. 

While I doubt the exact nature of these details is relevant, and the root cause itself may or may not be worth tracking down (since we're extending and providing alternate implementations for individual parts of JDT, that may be out of scope), but this patch at least attempts to allow us to deal with the results in a safer manner.

**Comment by stephan-herrmann** [comment]
> ... An ASTParser parses a file, creates the bindings, and then cleans up. For some reason, a later call to get a specific binding ends up looking for the scope object, which has been cleaned up already.

This works as designed, but many clients are surely not expecting this. This issue comes up every now and then, last mentioned in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1942#issuecomment-1920013919 (were the risk was reduced for one particular usecase).

https://bugs.eclipse.org/150657 even has a prototype of a feature that would allow clients to keep a "session" open to ensure that further type bindings can be resolved. Unfortunately we ran out of steam there. But perhaps you could connect to https://bugs.eclipse.org/bugs/show_bug.cgi?id=150657#c39

**Comment by robstryker** [comment]
Closing this issue as I've switched to code that fits the existing infrastructure better.
