### ISSUE TITLE
Incorrect visibility check

### ISSUE THREAD

**Issue by gzsombor** [eclipse-jdt/eclipse.jdt.core#339]
Hi,

 I've encountered code like this:

```
public class X {
	String z() { return Y.MSG; }

	@WithMsg(Y.MSG)
	static class Y {
		private final static String MSG = "msg";
	}
}
@interface WithMsg {
	String value();
}
```
This compiles fine in Javac, however ECJ reports that Y.MSG is not accessible from the **annotation**, the `z()` function is perfectly fine!
After I've debugged the problem, in the codebase, I've encountered a reference to [bug-316456](https://bugs.eclipse.org/bugs/show_bug.cgi?id=316456), which also refers to [bug-322741](https://bugs.eclipse.org/bugs/show_bug.cgi?id=322741) and [bug-185422](https://bugs.eclipse.org/bugs/show_bug.cgi?id=185422), they are issues reported in the Java 5 - 6 era (long long time ago). It seems that at that time, ECJ was patched to make it consistent with javac 1.6_21, which refused to compile this code. 
 For me, it's unclear what the JLS said at that time, from the comments of these tickets, it seemed that it was believed, that the original ECJ code was correct, and Javac was buggy, and the JLS was unclear.
 Luckily, the [JLS](https://docs.oracle.com/javase/specs/jls/se18/html/jls-6.html#jls-6.6.1-100-D-D) was made it more clear, Javac was fixed, so ECJ can be fixed too, if everyone agrees - basically reverting [this couple of lines](https://github.com/eclipse-jdt/eclipse.jdt.core/commit/07e87f4c2f12f879ec7ed457ed90a4c633cae710#diff-3a2d1e2c497232efc8681dcc4a71ae14fa93dd907f724ac5c2827e33ddf79680)

**Comment by stephan-herrmann** [comment]
Thanks for your investigation! I, too, see [bug-316456](https://bugs.eclipse.org/bugs/show_bug.cgi?id=316456) as deliberately injecting a bug in order to be compatible with javac. A tedious practice that was expected of ECJ time and again. I'm happy to read that this particular instance of bug injection can now be removed. 

In previous instances we went an extra mile to capture in the test also since which version javac was corrected, so that tests with -Drun.javac would pass in comparison against all "relevant" javac versions. @jarthana should we continue in this way, or is maintaining the `-Drun.javac=enabled` mode no longer considered relevant / feasible / desirable ?

**Comment by stephan-herrmann** [comment]
> In previous instances we went an extra mile to capture in the test also since which version javac was corrected, so that tests with -Drun.javac would pass in comparison against all "relevant" javac versions. @jarthana should we continue in this way, or is maintaining the `-Drun.javac=enabled` mode no longer considered relevant / feasible / desirable ?

As this is a question beyond the scope of this particular issue, I gave it a new home: #386
