### ISSUE TITLE
Unnecessary error marker for record constructor that uses varargs

### ISSUE THREAD

**Issue by rgrunber** [eclipse-jdt/eclipse.jdt.core#342]
From https://github.com/redhat-developer/vscode-java/issues/2640

Version: 2022-09 (4.25)
Build id: I20220817-1800

Given the following files, I see `The constructor Sneaker(String, int, int, int, int) is undefined` error marker on the `Sneaker` constructor invocation in `Main` but not in the `Sneaker` class itself. Furthermore, the error marker does not appear in the problems view, nor does it generate an error annotation on the file/folder(s)/projects in the package explorer, or even on the editor part. I've included a screenshot to show that. The code seems to compile and run just fine.

**Sneaker.java**
```
package org.running;
public record Sneaker(String brand, float price, int ... sizes) {
	public void test () {
		Sneaker sn = new Sneaker("Eclipse", 100, 9, 10, 11);
	}
}
```

**Main.java**
```
package org.running;
public class Main {
	public static void main(String[] args) {
		Sneaker sn = new Sneaker("Eclipse", 100, 1, 2, 3);
	}
}
```

![record-constructor](https://user-images.githubusercontent.com/1417342/186747660-f81f4c8f-87eb-48e2-b153-1ce20625fbca.png)

**Comment by srikanth-sankaran** [comment]
Note: The PR https://github.com/eclipse-jdt/eclipse.jdt.core/pull/4771 backs out the fix for https://github.com/eclipse-jdt/eclipse.jdt.core/issues/342 and comprehensively fixes the problem for both top level types and nested types. Basically the problem is that the varargs'ness of the record component is not persisted in the model (and cannot be reconstructed as a result)
