### ISSUE TITLE
The package xxx is accessible from more than one module

### ISSUE THREAD

**Issue by jdneo** [eclipse-jdt/eclipse.jdt.core#415]
After searching around, I found a detailed explanation of this problem: https://bugs.eclipse.org/bugs/show_bug.cgi?id=536928#c53

But, unfortunately, the [JDK side bug](https://bugs.openjdk.org/browse/JDK-8215739) is just there being inactive for ~4 years. It's embarrassing that although Eclipse did the right thing, the behavior is different from javac/build tools/other IDEs, which confuse users quite a lot. (I'm not blaming Eclipse, Eclipse did things right).

So I'm thinking that, is it possible that adding a preference to specify whether the module system should be enabled or not when the project is not a modular project, but the JDK is higher than `1.8`? In that case, user will not bother excluding dependencies or creating module description file. And more importantly, the behavior will be aligned with the build tools.

After the JDK bug is fixed, we can deprecate this preference.

**Comment by iloveeclipse** [comment]
> And more importantly, the behavior will be aligned with the build tools

You mean with the javac that has the bug in question?

> After the JDK bug is fixed, we can deprecate this preference.

Well, this means we build something in the compiler that will be broken as soon as javac fix will be there, and Eclipse again would need a fix.

Please ask Java maintainers on mailing list again to look at this bug, I **personally** don't think it is wise to make workarounds in Eclipse compiler for javac bugs that violate the Java specs.

@stephan-herrmann : WDYT?

**Comment by testforstephen** [comment]
Since the default behavior of ECJ still follows the strict JPMS rules, it doesn't break existing tools. I think it makes sense from a user perspective to have such a new preference to maintain compatibility with other popular Java build tools (e.g. Maven, Intellij IDEA).

**Comment by stephan-herrmann** [comment]
You might as well link to https://stackoverflow.com/questions/51094274/eclipse-cant-find-xml-related-classes-after-switching-build-path-to-jdk-10/53824670#53824670

* That bug in javac concerns one specific situation, the proposed change in #424 is way too broad.
* Since Java 9, there is no longer an option to avoid JPMS, even if all your code is in an unnamed module, JPMS rules do apply and the system libraries **are** modular.
* What the community needs to do most urgently: put pressure on Oracle to fix that bug. The votes on SO might be a good start :)
  * Makeing ecj bug compatible releases any such pressure and Java will degrade even more
* Any injection of a javac-bug into ecj comes at significant costs, it unnecessarily increases complexity, and there must be somebody to handle that complexity long term. Currently the team can barely handle the _necessary_ complexity. Its hard to convince committers to additionally invest in compensating other peoples bugs.
* Before a compiler might optionally ignore a JPMS rule, we must be very sure that the JVM will also skip the necessary validation: how does the JVM react to illegal split packages? How does it handle the case where one module is an unnamed module? There's probably more involved, because responsibility to enforce JPMS is split over VM and libraries (I think the relevant entity here is a Layer implementation).

FWIW: most build tools can be configured to use ecj instead of javac :)

**Comment by jdneo** [comment]
Hi @stephan-herrmann,

The SO answer is very helpful, I've voted for it 👍.

I work on JDT.LS. As a developer of Java tools, I totally understand your concerns, it is not feeling well when we introduce a workaround for a bug which is introduced by other components. On the other hand, as a user of JDT.Core, this issue really confused me at first since the compiled result is different from the build tool. I believe for most users, they may not spend times to search around and learn the story behind.

At the meantime, this issue bothers a lot of Eclipse Java users. (You can tell that from the result returned by the search engine, so many people answered the similar questions. It is so sad that after ~4 years, the javac bug is still there, and even not ETA for fixing 😞 ) I believe it can bring some values for users if this kind of projects can just work well out of box in Eclipse.

What about, we just add a preference as an internal one, not expose it in jdt.ui, but allow the downstream tools to change the behavior? We can just do some tests in the JDT.LS to see if this change works or not?

**Comment by stephan-herrmann** [comment]
From the "political" side, I'd say that implementing a workaround will mean we are giving up hopes for javac to be fixed in this regard. But I won't hold up a community that "wants" this bug. Still it would be quite important to also consider the **runtime** aspect of this: what happens when you try to launch an application with an illegal split package? Does this change when one of the modules involved is the unnamed module??

Implementationwise, I'd expect a workaround to meet these criteria:
* it should not introduce a lot of complexity to the JDT code base
* it should very specifically address this particular situation only.

Idea: The preference could cause this very specific problem to be downgraded from error to warning. Do you want to prepare a PR to that effect?

**Comment by jdneo** [comment]
> Still it would be quite important to also consider the runtime aspect of this: what happens when you try to launch an application with an illegal split package? Does this change when one of the modules involved is the unnamed module??

I found some explanation in a document of the jigsaw project: https://openjdk.org/projects/jigsaw/spec/sotms/#the-unnamed-module

In paragraph 2, it says:

```
An existing class-path application that compiles and runs on Java SE 8 will, thus,
compile and run in exactly the same way on Java SE 9, so long as it only uses standard,
non-deprecated Java SE APIs.
```

And paragraph 4 explains why:

```
If a package is defined in both a named module and the unnamed module then
the package in the unnamed module is ignored. This preserves reliable configuration
even in the face of the chaos of the class path, ensuring that every module still reads
at most one module defining a given package.
```

To verify the above statement, we can use this sample project: [helloworld.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/9638640/helloworld.zip)

- `mvn clean compile`
- `java -cp ".\target\classes\;<USER_HOME_PATH>\.m2\repository\xml-apis\xml-apis\1.0.b2\xml-apis-1.0.b2.jar" com.example.A`

JVM does not complain problem about the split package.

**Comment by stephan-herrmann** [comment]
> I found some explanation in a document of the jigsaw project: https://openjdk.org/projects/jigsaw/spec/sotms/#the-unnamed-module [...[

That's a very interesting find. It tells us that Oracle / Mark Reinhold had *intended* these things to work. This also helps to explain why javac accepts the thing. Unfortunately there is disagreement within Oracle: spec author Alex Buckley defined the opposite to be the case.

Did you see the cautionary note starting "_This document is slightly out of date_." Given that the promised update hasn't appeared in 6 years probably indicates that it is obsolete by now.

In case of conflict between specification (JLS) and implementation (javac), ecj generally adheres to the spec. But now that we know that there's intention behind the status of the implementation, adding that proposed preference sounds like reasonable compromise indeed.

**Comment by jdneo** [comment]
How about adding a preference that specify whether to ignore the unnamed module when we encounter a split package?

This preference has smaller impact than the original one and it's targeting the actual root cause of the problem.

@stephan-herrmann WDYT?

**Comment by jdneo** [comment]
Proposed a change at https://github.com/eclipse-jdt/eclipse.jdt.core/pull/424

**Comment by stephan-herrmann** [comment]
> Proposed a change at #424

The direction of the new approach looks good to me.

Will you be able to provide unit tests, too?

Also, you might want to update the description of the PR :)

A few more things come to mind:
* Perhaps the javadoc of the preference option should refer to the SOTM document to explain why this option exists?
* We'll also need an update of https://github.com/eclipse-platform/eclipse.platform.common/blob/master/bundles/org.eclipse.jdt.doc.isv/guide/jdt_api_options.htm
* How should the preference be surfaced?
  * In the UI?
  * As a command line switch for the batch compiler?

 I understand that for jdt.ls having an option in JavaCore / CompilerOptions could suffice, but for consistency I suggest we should make it configurable for users of all avatars of JDT (incl. Eclipse IDE, ecj batch compiler).

**Comment by jdneo** [comment]
Thank you for reviewing the PR @stephan-herrmann. The PR is updated.

A draft PR is raised as well for the document site: https://github.com/eclipse-platform/eclipse.platform.common/pull/78

**Comment by jdneo** [comment]
Close by #424

**Comment by stephan-herrmann** [comment]
For posterity: https://stackoverflow.com/a/74890645/4611488
:)

**Comment by econotom** [comment]
Hi! Can this setting be made "global", so we don't need to rembember to edit some prefs file for every workspace?
