### ISSUE TITLE
Wrong call hierarchy for jars with module conflict on compile classpath

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.core#675]
To reproduce:

1. Import projects from attached archive: [TestCallHierarchyBug.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/10544219/TestCallHierarchyBug.zip)
2. Open type test.Test.
3. Select the only field testField, right-click -> "Open Call Hierarchy".
4. Observe no matches.
5. Select testField again, right-click -> "References" -> "Workspace".
6. Observe the expected match, denoted as "potential match".

After debugging, it looks like `JavaSearchNameEnvironment.getModulesDeclaringPackage()` determines multiple declaring modules for `testpackage` (the unnamed module and `TestLibraryWithModule`). From there, a `SplitPackageBinding` is created for `testpackage` and `CompilationUnitScope.findImport()` will skip the import, creating a problem for the statement `import testpackage.TestClass`. This in turn results in a `MissingTypeBinding` for `TestClass` (during the call hierarchy computation). And so the search match in `test.Test.bar()` is considered an inaccurate match (also seen when computing workspace references of `testField`) and not reported for the call hierarchy.

The jars with the module conflict are on the compile **classpath**, not on the module path. So its odd to see this problem. If the 2 jars are on the module path, then there is a compile problem. So for the jars on a module path, the call hierarchy not finding anything would be expected. But not for the jars on the classpath.

**Comment by iloveeclipse** [comment]
In my eyes if "Reference search" can find calls, so "Call Hierarchy" should find them too, and vice versa.

Also from user point of view, *especially* if classpath/module path has some duplicates that need to be solved, one should be able to see where which code refers to what.

**Comment by iloveeclipse** [comment]
Just a note for myself after debugging & reviewing the code.

The key point in the bug and in the fix is that original code (added for 9+ support) **automatically** added "module" info to the search environment from the jar with module-info.class inside, **even** if that jar itself was used in a non-modular project (and placed on classpath).

So the fix adds differentiation between "modular" / "non-modular" classpath entries given to the search. So for a non modular classpath entry `JavaSearchNameEnvironment` doesn't try to add module info to the jar's `ClasspathLocation` and it doesn't land in `moduleToClassPathLocations` so later this info doesn't appear in `JavaSearchNameEnvironment.getModulesDeclaringPackage()` that confuses later code, and so on.
