### ISSUE TITLE
No completions for switch case labels in switch expressions inside lambda

### ISSUE THREAD

**Issue by gayanper** [eclipse-jdt/eclipse.jdt.core#697]
Take the following sample

```
	static Map<Thread.State, String> toMap(){
		return Stream.of(Thread.State.values()).collect(Collectors.toMap(Function.identity(), state -> {
			return switch (state) {
				case |
			};		
		}));
	}
```

Try to complete code near `|`, you don't get any completions

**Comment by gayanper** [comment]
@stephan-herrmann I found the root cause to be a assertion error for above code where the assertion was introduced by  https://bugs.eclipse.org/bugs/show_bug.cgi?id=535743. I guess it supposed to pop recovered lambda statements right ? But with incomplete switch case expression in place could that be causing this issue ?

**Comment by stephan-herrmann** [comment]
> I guess it supposed to pop recovered lambda statements right ?

You are referring to `popSnapShot()`? Unfortunately that issue is more involved, it's more like popping a full parser-state off a stack of branching universes :)  There is a brief mention of these snapshots in https://wiki.eclipse.org/JDT_Core_Programmer_Guide/Completion#fallBackToSpringForward.28.29

I you want me to take a closer look, please create a PR with a failing test.
