### ISSUE TITLE
Revisit formatter changes with introduction of 'when' clause in switch pattern expressions

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#75]
During the PR #74 , I left a failing test untouched since it may need some bigger formatter changes (not entirely sure). At the moment, it's only one test in FormatterRegressionTests._testBug573949(), but there could be others too. This needs investigation. Although I updated SpacePreparator.visit(GuardedPattern) to replace with the new token, this might more attention.

@mateusz-matela Please take a look.

**Comment by mateusz-matela** [comment]
I tried to enable the test and change the line
`case Triangle t&&(t.calculateArea() > 100) ->`
into
`case Triangle t when t.calculateArea() > 100 ->`.
The formatter now crashes, because the `when` token is not of type `TokenNameRestrictedIdentifierWhen` (131), it's `TokenNameIdentifier` (19). Is this something to be fixed in the `Scanner`? I see it has a method called `disambiguatedRestrictedIdentifierWhen()`, so it looks like it attempts to take care of it.

After we resolve this, I wonder how to handle whitespace around the `when` keyboard. Using the settings for `logical_operator` is no longer intuitive. I think we can always add spaces, they're usually necessary anyway (except for when the pattern or expression is in parentheis).
Also, in JEP some examples keep the `when` clause in the same line as the `case` clause, while others put in in a new line, I guess we'll need a new formatter setting for that.

**Comment by jarthana** [comment]
Thanks @mateusz-matela. I will look into that and report back. There's no rush to work on the formatter yet as we are still in early stages of compiler support. You don't mind keeping this on your list till then, do you?

**Comment by jarthana** [comment]
Scanner went through some changes for this keyword. I tried this again but still tests are failing but looks like a different error now.

**Comment by mateusz-matela** [comment]
I checked again and it turned out that the `Scanner` returns proper tokens when `previewEnabled` is set to true, so I did that in the failing test and it works now. It's possible that was the problem from the beginning.
Please verify in the PR that I set this option properly (will it stay there forever, or be removed when we're out of beta? maybe it should be set somewhere else globally?)

**Comment by jarthana** [comment]
Looks good. Whenever the feature moves from preview to standard, we can remove the option. So, we can close this now?

**Comment by mateusz-matela** [comment]
I think so, as long as we don't forget to remove the option when appropriate :)
