### ISSUE TITLE
Allow for duplicate package-info in main/test sources

### ISSUE THREAD

**Issue by ben-manes** [eclipse-jdt/eclipse.jdt.core#763]
> The type package-info is already defined

This appears to be a long standing issue that users have worked around, but I did not find it reported in bugzilla. Example discussions are https://github.com/netty/netty/issues/1234, [Apache Gora](https://issues.apache.org/jira/browse/GORA-511), [StackOverflow](https://stackoverflow.com/search?q=%22The+type+package-info+is+already+defined%22), [Eclipse Community Forums](https://www.eclipse.org/forums/index.php/t/1084125/), [Experts Exchange](https://www.experts-exchange.com/questions/26897613/JavaDoc-Package-info-java-Eclipse-Maven-Checkstyle.html), and so on. This differs from class shadowing that relies on classpath ordering to resolve duplicates, as Eclipse won't complain if the two source sets contain the same class name.

The best workaround in those discussions is to add a `.classpath` exclusion.

This issue is either to confirm that is Eclipse's preferred solution (so that others can discover it easier) or to remove the compilation error.

<details>
<summary>Example Gradle exclusion</summary>

```gradle
eclipse.classpath.file.whenMerged {  
  var sourceFolders = entries.findAll { it instanceof SourceFolder }
  for (var sourceFolder : sourceFolders) {
    if (sourceFolder.path != 'src/main/java') {
      sourceFolder.excludes += '**/package-info.java'
    }
  }
}
```

</details>

**Comment by stephan-herrmann** [comment]
Since different source folders within a project contribute to the same (split) packages, reporting duplication as an error is the natural thing. Note that `package-info.java` may hold annotations, and with duplication of that file, asking a package for its annotations would not be a reliable operation.

Unless we are shown a relevant use case where it is crucial to define duplicate `package-info.java` for the same package, I don't see anyone in JDT working on this. Hence, those who need to have such duplicate files should indeed exclude them from the JDT classpath.
