### ISSUE TITLE
[20] Fix and enable the commented out tests in SwitchPatternTest

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#932]
As many as 19 tests were commented out during pull #556. If the tests indeed need to be fixed, we should do that and capture the new behavior in those tests rather than just commenting them out.

@mpalat please take a look.

**Comment by mpalat** [comment]
@jarthana  please take a look at https://github.com/eclipse-jdt/eclipse.jdt.core/issues/635 - As you can see, this issue was created separately to address these failures. There is one omission - thanks for pushing for a relook - have raised https://github.com/eclipse-jdt/eclipse.jdt.core/issues/933 to address that.

And here are the details for the rest of the ones:
574719 - 6 - grammar change - this is no longer relevant.
575241 - 3 - already enabled
575356 - 2 - grammar change - Only one test is relevant - that is enabled - other one disabled
575047 - 1 - already enabled
575051 - 1 - not relevant with the fourth preview - hence disabled
578553 - 1 - already enabled
556    - 2 - already enabled

**Comment by jarthana** [comment]
Here's why I think they are relevant (at least the testBug574719* ones)

The test code now fails with the following compiler error:

A 'default' can occur after 'case' only as a second case label expression and that too only if 'null' precedes  in 'case null, default'

This is a new error message that was introduced by the PR I mentioned. Any guess how many tests test this error message?
  - Zero.

I think even other tests can be made relevant by adjusting them to test the new behavior. Last resort should be removing them, instead of leaving lot of stale code.

**Comment by mpalat** [comment]
> This is a new error message that was introduced by the PR I mentioned. Any guess how many tests test this error message?
> 
> * Zero.


@jarthana - that observation is wrong. Check testIssue_556_003

**Comment by jarthana** [comment]
> @jarthana - that observation is wrong. Check testIssue_556_003

My bad. I didn't account for the escaping. In that case, the tests that are no longer relevant can be removed if you are sure these are covered elsewhere.

**Comment by mpalat** [comment]
> > @jarthana - that observation is wrong. Check testIssue_556_003
> 
> My bad. I didn't account for the escaping. In that case, the tests that are no longer relevant can be removed if you are sure these are covered elsewhere.

@jarthana Thanks! However, am just holding on to these commented tests until the Switch Pattern is standardized - expected to be in 21 so that if we have some of these becoming relevant again, we can just enable them easily. We can remove them once it is standardized.  Please bear with this until then.

**Comment by jarthana** [comment]
Sure, then let's keep this issue so we can track this. I will remove the milestone.

**Comment by jarthana** [comment]
I have enabled and fixed some tests and deleted some that are no longer relevant. Closing now.
